#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 公务员考试培训.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公务员考试培训"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 考情与政策维度
  9.2 岗位竞争维度
  9.3 备考策略维度
  9.4 工具与课程维度
  9.5 行业商业维度
  9.6 AI+教育维度
  9.7 体制内认知维度

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "考情与政策维度"
  "岗位竞争维度"
  "备考策略维度"
  "工具与课程维度"
  "行业商业维度"
  "AI+教育维度"
  "体制内认知维度"
)
declare -a DIM_QUESTIONS=(
  "国考/省考最新公告、大纲变化、招录政策趋势"
  "目标岗位的报录比、历年进面分数线、竞争格局"
  "笔试(行测+申论)+面试的备考方法论和时间规划"
  "培训机构/APP/AI 工具的对比选型"
  "三巨头竞争格局、商业模式（协议班/AI 班/OMO）、行业趋势"
  "AI 工具在公考培训中的应用现状和边界"
  "公务员职业发展、体制内工作实情、考公动机分析"
)
declare -a DIM_SOURCES=(
  "用户提到具体考试年份或政策变化"
  "用户问「这个岗位值得报吗」或选岗相关问题"
  "用户问「怎么备考」或具体科目提分方法"
  "用户问「用什么工具」或「报哪家课」"
  "用户从从业者/投资人视角讨论行业"
  "用户问 AI 批改/AI 面试/智能学习路径相关问题"
  "用户问「考上之后怎样」或职业规划相关"
)
declare -a DIM_OUTPUT_FORMATS=(
  "从 scs.gov.cn / 各省人社厅官网获取一手公告，对比往年变化"
  "从相对面/粉笔报岗数据查询实时竞争比，对比历史数据"
  "按 ROI 排序推荐学习路径，区分入门/资深/冲刺不同阶段"
  "按考生身份×预算×短板维度推荐工具组合，标注优劣势"
  "引用上市公司年报数据+行业报告，区分一手/二手"
  "列出具体 AI 产品、定价、效果数据，明确标注 AI 能做和不能做的边界"
  "引用播客/论坛中体制内人的一手叙事，标注幸存者偏差"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
