#!/usr/bin/env bash
# topic-2.sh — 决策 决策助手 for CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。"
TOPIC="决策"

usage() {
  cat <<EOF
topic-2.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-2.sh             # interactive
  ./topic-2.sh --dry-run   # walk through but no file
  ./topic-2.sh --json      # JSON to stdout
  ./topic-2.sh --explain   # show backing playbook rules + mental models
  ./topic-2.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 决策 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 ≥ 5% 自由现金流去向决策 → 则 : 则在 5 levers (内部再投 / 并购 / 派息 / 回购 / 还债) 同台用 own hurdle rate
  • 如果 文化 / 价值观决策 (culture as OS) → 则 : 则文化不是写在墙上的 values, 是 hire-and-fire 决策的累积; talent density 高

相关心智模型:
  • 资本配置 = CEO 最高杠杆工作 (Capital Allocation as the #1 Job): 「CEO 一辈子要做的几十个决策中, 资本配置 (5 levers: 内部再投 / 并购 / 派息 / 回购 / 还债) 的复利结果决定企业 20 年后的市值排序; 不算 hurdle rate / 
  • 战略转折点 + 主动 paranoia (Strategic Inflection Point + Paranoia as Discipline): 「10x 力 (技术 / 竞争 / 监管 / 用户行为) 改变行业基本面时, CEO 必须最先识别 + 主动毁掉一部分老业务穿越 SIP (Intel 1985 退 DRAM / 任正非 1998 华

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "≥ 5% 自由现金流去向决策"
  "文化 / 价值观决策 (culture as OS)"
)
declare -a RULE_ACTIONS=(
  ": 则在 5 levers (内部再投 / 并购 / 派息 / 回购 / 还债) 同台用 own hurdle rate (best alternative return) 比较不预设答案; 写 1-pager thesis 上 board; 年度致股东信公开决策逻辑让投资人理解 own 框架"
  ": 则文化不是写在墙上的 values, 是 hire-and-fire 决策的累积; talent density 高之后才能 context-not-control; 文化抗拒者必 fire; 文化文档 (Netflix Culture Memo / Amazon LP / Huawei 心声社区) 是「契约 not perks」; 必须 explicit + 持续重申 (Town Hall + 致全员信) + 高管 model behavior"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-2-decision"
fi
