#!/usr/bin/env bash
# topic-3.sh — 老年 决策助手 for 银发教育.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="银发教育"
TOPIC="老年"

usage() {
  cat <<EOF
topic-3.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-3.sh             # interactive
  ./topic-3.sh --dry-run   # walk through but no file
  ./topic-3.sh --json      # JSON to stdout
  ./topic-3.sh --explain   # show backing playbook rules + mental models
  ./topic-3.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 老年 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 老年大学"一座难求" → 则 : 则优先扩容不是建新校 — 开设社区分校/送教上门/在线分校, 比新建大型校区成本低 10 倍且覆盖面广
  • 如果 银发教育项目需要说服政府或投资人 → 则 : 则用"健康经济学"逻辑而非"教育公平"逻辑 — 每 1 元老年教育投入约可减少 约 3-5 元医疗和养老服务支出(通

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "老年大学\"一座难求\""
  "银发教育项目需要说服政府或投资人"
)
declare -a RULE_ACTIONS=(
  ": 则优先扩容不是建新校 — 开设社区分校/送教上门/在线分校, 比新建大型校区成本低 10 倍且覆盖面广"
  ": 则用\"健康经济学\"逻辑而非\"教育公平\"逻辑 — 每 1 元老年教育投入约可减少 约 3-5 元医疗和养老服务支出(通过延迟失能/减少孤独/降低抑郁)"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-3-decision"
fi
