#!/usr/bin/env bash
# topic-1.sh — 学员 决策助手 for 银发教育.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="银发教育"
TOPIC="学员"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 5 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 学员 主题下的 playbook 规则组合成交互树。

基于 5 条规则:
  • 如果 学员数字素养极低(功能机用户/从未用过智能手机) → 则 : 则从"防诈骗"而非"功能教学"入门 — 先教识别骗局建立安全感, 再教微信/支付宝基础操作
  • 如果 在低预算下需要快速开展在线教学 → 则 : 则微信群 + 小程序是最低门槛方案 — 不要上复杂系统(学员学不会), 微信群语音/视频 + 班级圈小程序 + 作业
  • 如果 要评估教学效果但学员抗拒考试 → 则 : 则用"作品展示"替代传统考核 — 书画展/短视频作品集/合唱演出/摄影展既是学习成果也是社交激励
  • 如果 新建一所老年大学 → 则 : 则先定位再建设 — 确定服务半径(社区级/区级/市级)/目标学员画像(60-70 vs 70-80 vs 80+)/
  • 如果 课程内容更新缓慢/学员流失 → 则 : 则引入"学员反向出题"机制 — 让学员提出想学什么(而非管理者猜), 定期做需求调研

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "学员数字素养极低(功能机用户/从未用过智能手机)"
  "在低预算下需要快速开展在线教学"
  "要评估教学效果但学员抗拒考试"
  "新建一所老年大学"
  "课程内容更新缓慢/学员流失"
)
declare -a RULE_ACTIONS=(
  ": 则从\"防诈骗\"而非\"功能教学\"入门 — 先教识别骗局建立安全感, 再教微信/支付宝基础操作"
  ": 则微信群 + 小程序是最低门槛方案 — 不要上复杂系统(学员学不会), 微信群语音/视频 + 班级圈小程序 + 作业提交即可"
  ": 则用\"作品展示\"替代传统考核 — 书画展/短视频作品集/合唱演出/摄影展既是学习成果也是社交激励"
  ": 则先定位再建设 — 确定服务半径(社区级/区级/市级)/目标学员画像(60-70 vs 70-80 vs 80+)/核心课程方向(文艺/数字/健康/技能)再做硬件规划"
  ": 则引入\"学员反向出题\"机制 — 让学员提出想学什么(而非管理者猜), 定期做需求调研"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
