#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 中国网站备案 与 互联网内容合规 (含 ICP 备案 主体+网站 / 公安备案 / ICP 经营许可证 增值电信 / 域名实名认证 / APP 备案 2024 工信部新规 / 等级保护测评 网安 / 算法推荐 + 深度合成 + 生成式 AI 备案 网信办 / 数据出境 + 个保法 + 数安法 合规联动 / 变更注销转移跨省迁移 — 不含 通用法律咨询 / 海外域名注册 / 网络营销 SEO / 翻墙 VPN).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="中国网站备案 与 互联网内容合规 (含 ICP 备案 主体+网站 / 公安备案 / ICP 经营许可证 增值电信 / 域名实名认证 / APP 备案 2024 工信部新规 / 等级保护测评 网安 / 算法推荐 + 深度合成 + 生成式 AI 备案 网信办 / 数据出境 + 个保法 + 数安法 合规联动 / 变更注销转移跨省迁移 — 不含 通用法律咨询 / 海外域名注册 / 网络营销 SEO / 翻墙 VPN)"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 业务类型 与 法律性质判定
  9.2 三横三纵 九宫格 现状评估
  9.3 主体所属省份 + 通管局 选型
  9.4 接入商 + 云厂商 选型
  9.5 数据 + 算法 + 大模型 + 跨境 联动
  9.6 特殊行业许可联动
  9.7 持续合规 + 抽查应对 准备

背后的心智模型:
  • 三横三纵立体备案框架: 任何一个跑在中国大陆境内的 网站 / APP / 小程序 / SaaS 都同时落在 三横 (ICP 备案 + 公安备案 + 等级保护测评) × 三纵 (主体 + 网站 + 经营性升级) 的九宫格里, 
  • 接入商责任体系 (中国独有制度): 中国法定 ICP 备案的执行单位是 接入服务商 (云厂商 / IDC), 不是 申请人自己 — 站长不能直接向工信部提交, 必须 通过 阿里云 / 腾讯云 / 华为云 等接入商 完成 信息核验 + 提
  • 各省通管局执行口径差异 (30%+ 区域差): 同一主体 + 同一备案材料, 上海 / 北京 / 广东 / 浙江 / 江苏 通管局的 审核严格度 + 通过率 + 反馈速度 与 二三线省份 差异 ≥ 30% (业内估), 同一省份 不同时期 (尤其 

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "业务类型 与 法律性质判定"
  "三横三纵 九宫格 现状评估"
  "主体所属省份 + 通管局 选型"
  "接入商 + 云厂商 选型"
  "数据 + 算法 + 大模型 + 跨境 联动"
  "特殊行业许可联动"
  "持续合规 + 抽查应对 准备"
)
declare -a DIM_QUESTIONS=(
  "网站 / APP / 小程序 / SaaS / 大模型 / 视频 / 直播 / 跨境 哪类? 经营性 vs 非经营性? 涉及 算法推荐 + 深度合成 + AIGC + 视听 + 文化 + 新闻 + 出版 任一?"
  "主体 + 网站 + 经营 三纵 × 备案 + 公安 + 等保 三横 九宫格, 每格 现状 + 谁来做 + 时间线"
  "业务实际所在 + 同省接入商网络 + 该省通管局历史 拒批率 + 反馈速度 三因素"
  "备案能力 + vendor docs 详尽度 + 各省通管局对接经验 + 业务规模 匹配"
  "业务 涉及 数据出境? 算法推荐? 大模型? AIGC? 跨境母公司?"
  "业务 落在 金融 / 教培 / 医疗 / 视听 / 出版 / 文化 / 新闻 / 直播带货 等 强监管 行业?"
  "上线后 季度自查 + 年度整改报告 + 抽查应对 + 法务 + 安全员 24h 应急 是否 已设立?"
)
declare -a DIM_SOURCES=(
  "beian.miit.gov.cn + cac.gov.cn 当年 通知; 律所 (君合 / 中伦 / 金杜) alerts 当年 业态 解读; 工信部 电信业务分类目录 2015 修订"
  "站长 + 接入商 + 法务 + 测评机构 直接对接; beian.miit.gov.cn / www.beian.gov.cn / 等保 测评机构 系统"
  "各省通管局 .gov.cn 子站 (shca / bjca / gdca / zjca / jsca); 业内律所 alerts (中伦 / 君合 / 金杜) 各省口径解读"
  "阿里云 help.aliyun.com + 腾讯云 cloud.tencent.com/document + 华为云 support.huaweicloud.com + 京东云 docs.jdcloud.com; 中小厂 (UCloud / 青云 / 金山云) vendor docs 实际深度"
  "网信办 cac.gov.cn 当年 数据出境 通知; 律所 跨境 alerts; 国际律所 中国办公室 (DLA Piper / Baker McKenzie) alerts; PIPL / DSL 学者 论文 (周汉华 / 张新宝)"
  "行业主管部门 .gov.cn 当年 准入政策 (央行 / 教育部 / 卫健委 / 国家广电总局 / 网信办内容)"
  "工信部 + 公安部 + 网信办 历年 抽查 节奏; 律所 处罚案例 alerts; 滴滴 / 知网 / 字节 等 反面 案例"
)
declare -a DIM_OUTPUT_FORMATS=(
  "一句话判定 = \"经营性 / 非经营性 + 行政许可 / 行政备案 + 加挂 哪些 行业特许\""
  "九宫格表 + 每格 \"已完成 / 进行中 / 未开始 / 不适用\" + Owner + 时间线"
  "候选 3 省份 + 推荐 1 个 + 推荐理由 + 备选风险"
  "主接入商 + 备份接入商 + 接入合同要点 (退出 / 转移 / 多省接入)"
  "数据出境路径 (CAC 评估 / 标准合同 / 认证) + 算法备案 + 大模型 备案 + 跨境母公司 配合方案"
  "行业特许清单 + 申请门槛 (注册资本 / 人员 / 接入资源) + 申请时间线"
  "持续合规 角色矩阵 (法务 + 合规 + 安全员) + 应急流程 + 季度自查 checklist"
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
