#!/usr/bin/env bash
# 5-120-135.sh — 行测备考工作流 (5 模块学习顺序/时间分配/120 分钟 135 题策略) SOP walkthrough for 公务员考试培训.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公务员考试培训"
WORKFLOW="行测备考工作流 (5 模块学习顺序/时间分配/120 分钟 135 题策略)"

usage() {
  cat <<EOF
5-120-135.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./5-120-135.sh             # interactive
  ./5-120-135.sh --dry-run
  ./5-120-135.sh --json
  ./5-120-135.sh --explain
  ./5-120-135.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "行测备考工作流 (5 模块学习顺序/时间分配/120 分钟 135 题策略)" 工作流。

入门 SOP 共 6 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "熟悉 5 大模块: 常识判断 (20 题) / 言语理解与表达 (40 题) / 数量关系 (15 题) / 判断推理 (40 题) / 资料分析 (20 题), 先做 1 套真题摸底, 确定各模块正确率"
  "学习顺序 (按投入产出比): 资料分析 (提分最快, 技巧性强) → 判断推理 (逻辑/图形/定义/类比 4 个子模块) → 言语理解 (阅读量大, 需语感积累) → 数量关系 (难度最高, 选择性放弃部分) → 常识判断 (短期提分空间小, 靠积累)"
  "每日训练: 精做 1 个模块 30-50 题 (限时), 做完对答案 + 看解析 + 归纳题型规律, 每周 1 次全模块限时模考"
  "考场做题顺序 (行业共识): 常识判断 (5-8 分钟, 不纠结直接选) → 资料分析 (20-25 分钟, 必须全做) → 判断推理 (30-35 分钟) → 言语理解 (25-30 分钟) → 数量关系 (15-20 分钟, 先挑简单题) → 留 5-10 分钟涂卡检查"
  "建立错题本: 按模块分类, 记录错因 (知识盲区/审题失误/计算错误/时间不够), 每周回顾 1 次"
  "冲刺期策略: 放弃数量关系中最难的 3-5 题 (蒙同一选项), 把时间让给资料分析和判断推理保正确率"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "5-120-135-walkthrough"
fi
