#!/usr/bin/env bash
# ai-ai-ai.sh — AI+公考新工作流 (AI 批改/AI 面试/智能路径) SOP walkthrough for 公务员考试培训.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公务员考试培训"
WORKFLOW="AI+公考新工作流 (AI 批改/AI 面试/智能路径)"

usage() {
  cat <<EOF
ai-ai-ai.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./ai-ai-ai.sh             # interactive
  ./ai-ai-ai.sh --dry-run
  ./ai-ai-ai.sh --json
  ./ai-ai-ai.sh --explain
  ./ai-ai-ai.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "AI+公考新工作流 (AI 批改/AI 面试/智能路径)" 工作流。

入门 SOP 共 6 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "选择 AI 工具: 粉笔 AI 智能老师 (自研垂域大模型 + DeepSeek, 覆盖行测/申论/面试, T03-S031) / 半月谈 AI 申论批改 (新华社背景, 免费 5 次, T03-S028 from T02) / 智蛙面试 AI (20000+ 真题, 五维雷达图, T02-S020) / 通用大模型 (DeepSeek/豆包/ChatGPT, 免费, 适合素材整理和框架搭建)"
  "AI 辅助行测: 用粉笔 AI 刷题系统班做个性化诊断 — AI 分析历史答题数据, 识别薄弱知识点, 推送针对性练习题, 实现「千人千面」刷题路径; 定价 680 元 (T03-S023)"
  "AI 辅助申论: 写完答案后用 AI 批改工具提交 — AI 对比官方阅卷标准和高分范文库, 1 分钟内输出诊断报告 (要点命中率/逻辑连贯性/语言规范性/字数), 指出遗漏要点和表达改进方向"
  "AI 辅助面试: 用 AI 面试工具对练 — 选择题型, AI 出题 → 考生语音作答 → AI 实时转写 + 多维度评分 (内容/逻辑/语言/仪态), 生成改进建议; 粉笔面试 AI 单次 29 元, 智蛙 AI 按月/季订阅"
  "AI 辅助时政: 用通用大模型整理时政素材 — 输入「请整理本月公考热点, 按五位一体分类, 每个热点写 100 字摘要 + 可用于申论的角度」, AI 输出结构化素材卡片, 原 1 晚工作量压缩至 20 分钟 (T03-S032)"
  "AI 工具边界: AI 批改适合「练习阶段」快速反馈, 不能替代真人教师对复杂题目的深度解析; AI 面试适合「初期脱敏」, 高阶阶段仍需真人对练感受考场压力; 通用大模型可能编造不存在的政策或案例, 必须人工核实"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "ai-ai-ai-walkthrough"
fi
