#!/usr/bin/env bash
# ip-b.sh — 名师 IP 打造工作流 (教研 → B站/抖音 → 粉丝转化 → 变现) SOP walkthrough for 公务员考试培训.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公务员考试培训"
WORKFLOW="名师 IP 打造工作流 (教研 → B站/抖音 → 粉丝转化 → 变现)"

usage() {
  cat <<EOF
ip-b.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./ip-b.sh             # interactive
  ./ip-b.sh --dry-run
  ./ip-b.sh --json
  ./ip-b.sh --explain
  ./ip-b.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "名师 IP 打造工作流 (教研 → B站/抖音 → 粉丝转化 → 变现)" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "确定 IP 定位: 选择擅长领域 (行测某模块 / 申论 / 面试) + 个人风格 (技巧流 / 逻辑流 / 段子手 / 温和鼓励型), 研究已成功的公考名师案例 (如花生十三: B 站 317 万粉丝, 行测技巧导向, T03-S035)"
  "内容矩阵设计: 短视频 (1-3 分钟, 单个知识点/解题技巧, 发抖音/B站/快手) + 中长视频 (10-30 分钟, 模块精讲, 发 B 站) + 直播 (1-2 小时, 答疑/带练/模考解析), 保持每周 3-5 条更新频率"
  "爆款选题: 围绕「高搜索量 + 强痛点」选题 — 如「行测资料分析 30 秒出答案」/「申论万能开头 3 个模板」/「面试紧张到大脑空白怎么办」, 标题用数字+痛点+解决方案结构"
  "拍摄与制作: 初期用手机+三脚架+自然光即可, 画面以「真人出镜+手写板/PPT」为主, 剪辑节奏快 (每 5-8 秒一个信息点), 字幕必加"
  "粉丝运营: 评论区逢问必答, 建立粉丝群 (QQ/微信/飞书), 每周 1 次群内答疑, 用「免费资料包」做留存 (真题合集/笔记/时政汇编)"
  "流量转化: 粉丝积累到 1-5 万后开始变现 — 低价引流课 (9.9-49 元, 单模块精讲) → 系统班 (500-1500 元) → 高价面授/一对一 (5000-30000 元), 或挂机构课程分佣"
  "持续迭代: 根据数据 (播放量/完播率/转化率) 优化内容方向, 考试季加大更新频率, 非考试季做职场/考编等泛内容维持热度"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "ip-b-walkthrough"
fi
