#!/usr/bin/env bash
# workflow-3.sh — 面试备考工作流 (结构化面试 → 题型 → 框架 → 对练) SOP walkthrough for 公务员考试培训.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公务员考试培训"
WORKFLOW="面试备考工作流 (结构化面试 → 题型 → 框架 → 对练)"

usage() {
  cat <<EOF
workflow-3.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-3.sh             # interactive
  ./workflow-3.sh --dry-run
  ./workflow-3.sh --json
  ./workflow-3.sh --explain
  ./workflow-3.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "面试备考工作流 (结构化面试 → 题型 → 框架 → 对练)" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "确认面试形式: 结构化面试 (最常见, 约 80% 岗位) / 结构化小组 (税务系统为主, 3 人一组轮流答题 + 互评) / 无领导小组讨论 (少数部委), 查目标岗位往年面试形式"
  "掌握 6 大题型框架: 综合分析 (表态 + 分析原因/影响 + 对策 + 总结) / 组织管理 (事前-事中-事后, 明确目标/对象/方式/步骤) / 应急应变 (分清轻重缓急, 先处理紧急事项) / 人际关系 (表态 + 反思 + 沟通 + 改进) / 现场模拟 (带入角色, 有称谓/有情感/有对策) / 岗位匹配 (结合个人经历 + 岗位需求)"
  "每日答题训练: 计时练习 (思考 1-2 分钟, 答题 2-3 分钟/题, 共 4-5 题/场), 全程录音或录像, 答完回听纠正口头禅/逻辑断层/超时问题"
  "组建对练小组: 3-5 人小组, 每天固定时间互当考官, 轮流出题-答题-点评, 模拟真实考场压力; 无条件时用智蛙面试等 AI 对练工具"
  "参加至少 2 次全真模拟: 线下模拟 (穿正装, 面对 5-7 名陌生考官, 含候考/抽签/入场/答题全流程) 或机构模考班, 重点练心理素质和现场感"
  "素材库建设: 按题型分类积累 30-50 个答题素材 (政策案例/个人经历/名言金句), 确保每类题型有 5-8 个可调用的论据"
  "考前 3 天: 回顾高频题型, 准备 1 段 30 秒自我介绍, 确认着装/交通/证件, 保持正常作息"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-3-walkthrough"
fi
