#!/usr/bin/env bash
# workflow-1.sh — 考生备考全流程 (报名 → 笔试 → 面试 → 上岸) SOP walkthrough for 公务员考试培训.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公务员考试培训"
WORKFLOW="考生备考全流程 (报名 → 笔试 → 面试 → 上岸)"

usage() {
  cat <<EOF
workflow-1.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-1.sh             # interactive
  ./workflow-1.sh --dry-run
  ./workflow-1.sh --json
  ./workflow-1.sh --explain
  ./workflow-1.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "考生备考全流程 (报名 → 笔试 → 面试 → 上岸)" 工作流。

入门 SOP 共 9 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "确定考试类型: 国考 (每年 10 月报名/11 月笔试) 或省考 (多数省份 2-3 月报名/3-4 月笔试), 登录国家公务员局 (scs.gov.cn) 或各省人事考试网下载公告和大纲"
  "选岗报名: 下载职位表 (Excel), 按学历/专业/政治面貌/基层经历 4 个硬条件筛选, 关注报录比 (竞争比低于 50:1 为合理区间), 在规定窗口期 (通常 10 天) 内提交申请并通过资格审查"
  "基础阶段 (考前 3-6 个月): 系统学习行测 5 模块 + 申论 4 题型, 用粉笔/华图/中公任一家系统班建立知识框架, 每天 3-4 小时"
  "强化阶段 (考前 1-3 个月): 按模块刷真题 (近 5 年国考 + 目标省份真题), 每周 1 次全真模考 (粉笔模考大赛/华图模考), 建立错题本, 申论开始大量练笔"
  "冲刺阶段 (考前 2-4 周): 每周 2-3 次全真模考, 回归错题, 时政热点集中背诵, 调整做题顺序和时间分配"
  "笔试: 行测 120 分钟 + 申论 180 分钟 (国考) 或 150 分钟 (多数省考), 带齐准考证/身份证/2B铅笔/黑色签字笔"
  "查成绩/进面: 笔试成绩公布后 (通常 1 个月内), 确认是否进入面试名单 (国考一般按 1:3 或 1:5 比例), 缴纳面试确认"
  "面试备考 (通常 15-30 天): 结构化面试为主, 每天对练 2-3 小时, 录像复盘, 参加 1-2 次线下模拟"
  "面试 → 体检 → 政审 → 公示 → 录用: 面试成绩与笔试按比例合成总分, 体检按公务员录用体检通用标准执行, 政审考察品行/信用/违法记录"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-1-walkthrough"
fi
