#!/usr/bin/env bash
# workflow-7.sh — 选岗报名决策工作流 (职位表 → 条件筛选 → 报录比 → 确定岗位) SOP walkthrough for 公务员考试培训.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公务员考试培训"
WORKFLOW="选岗报名决策工作流 (职位表 → 条件筛选 → 报录比 → 确定岗位)"

usage() {
  cat <<EOF
workflow-7.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-7.sh             # interactive
  ./workflow-7.sh --dry-run
  ./workflow-7.sh --json
  ./workflow-7.sh --explain
  ./workflow-7.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "选岗报名决策工作流 (职位表 → 条件筛选 → 报录比 → 确定岗位)" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "下载职位表: 国考职位表从国家公务员局专题网站 (scs.gov.cn 或 bm.scs.gov.cn) 下载 Excel 文件; 省考从各省人事考试网下载; 2025 国考 39721 个岗位/招录 39721 人 (T03-S028)"
  "硬条件筛选 (淘汰不符合项): 在 Excel 中依次筛选: 学历 → 学位 → 专业 (参考专业目录对照表) → 政治面貌 → 基层工作经历 → 户籍限制 → 年龄 → 其他条件 (证书/语言/性别), 筛完后保留所有可报岗位"
  "地域偏好筛选: 按工作地点优先级排序 — 省会/直辖市 > 地级市 > 县区 > 乡镇, 或按回家乡/目标城市/不限地域三档标注"
  "岗位性质评估: 了解目标单位层级 (中央/省/市/县/乡) 和部门属性 (综合管理类/行政执法类/专业技术类), 省直/市直岗晋升空间和薪资优于基层岗, 但竞争也更激烈"
  "竞争比分析: 利用报岗数据工具 (相对面 xduim.com / 粉笔报岗大数据 / 上岸鸭竞争比查询) 实时查看各岗位报名人数和竞争比, 长三角珠三角热门岗可达 500:1+, 中西部基层岗低至 1:12 (T03-S029)"
  "报名时机策略: 不要第一天报名 (信息不全), 在报名截止前 2-3 天提交 — 此时多数岗位报名数据已公开, 可选择竞争比相对合理的岗位; 确认资格审查通过后不可改报"
  "最终决策: 综合「通过概率 (竞争比 + 自身实力) × 岗位价值 (发展前景 + 生活质量)」做决策, 目标: 找到竞争比在 30:1-80:1 之间且自身条件匹配度高的岗位"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-7-walkthrough"
fi
