#!/usr/bin/env bash
# workflow-6.sh — 协议班运营工作流 (招生 → 授课 → 退费/录取) SOP walkthrough for 公务员考试培训.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公务员考试培训"
WORKFLOW="协议班运营工作流 (招生 → 授课 → 退费/录取)"

usage() {
  cat <<EOF
workflow-6.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-6.sh             # interactive
  ./workflow-6.sh --dry-run
  ./workflow-6.sh --json
  ./workflow-6.sh --explain
  ./workflow-6.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "协议班运营工作流 (招生 → 授课 → 退费/录取)" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "产品设计: 设定协议班类型 — 「笔试协议班」(笔试不过退 X%) / 「笔面协议班」(面试不过退 X%) / 「全程协议班」(未录用退 X%), 定价区间 1-5 万 (线上) / 2-8 万 (线下面授) / 1.5-3.9 万 (基地班含食宿), 明确退费比例和条件"
  "招生转化: 通过免费公开课/模考大赛/短视频引流, 课程顾问电话+微信跟进, 核心话术围绕「保障性」— 强调退费条款降低决策门槛; 注意: 2021 年五部门通知禁止广告出现「考不过退款」保证性承诺 (T03-S020)"
  "签约与缴费: 签署培训协议 (明确课时/退费条件/退费流程/退费时限), 支持全款/分期/助学贷款, 预收学费计入「合同负债」科目"
  "授课交付: 按协议约定课时交付教学 (笔试系统班 + 冲刺班 + 模考 + 面试特训), 全程记录学员出勤/作业/模考成绩, 作为退费审核依据"
  "考试结果判定: 笔试成绩公布后, 未进面学员触发退费流程; 面试后, 未录用学员触发退费流程; 录用学员转为「成功案例」用于后续招生"
  "退费处理: 学员提交退费申请 + 成绩证明 + 协议原件, 机构审核后按约定比例退款, 行业惯例退款周期 30-90 天; 实际中部分机构存在拖延/分期/以物抵债等争议做法 (T03-S019/T03-S021)"
  "数据复盘: 统计本期协议班通过率/退费率/实际利润率, 评估产品是否可持续, 调整下期定价和退费比例"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-6-walkthrough"
fi
