#!/usr/bin/env bash
# workflow-5.sh — 模考组织工作流 (出题 → 组卷 → 考试 → 评分 → 数据分析) SOP walkthrough for 公务员考试培训.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公务员考试培训"
WORKFLOW="模考组织工作流 (出题 → 组卷 → 考试 → 评分 → 数据分析)"

usage() {
  cat <<EOF
workflow-5.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-5.sh             # interactive
  ./workflow-5.sh --dry-run
  ./workflow-5.sh --json
  ./workflow-5.sh --explain
  ./workflow-5.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "模考组织工作流 (出题 → 组卷 → 考试 → 评分 → 数据分析)" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "出题: 教研团队根据最新考情命制原创题 (行测 130-135 题 + 申论 4-5 题), 或从题库中按知识点/难度/区分度组卷, 确保题目分布与真题一致 (各模块题量/占比/难度梯度)"
  "审题: 3 人交叉审核 (出题人自审 → 同行审 → 教研负责人终审), 检查答案准确性/题干歧义/选项合理性/政治敏感性, 申论参考答案需标注采分点和评分标准"
  "组卷与排版: 按真题版式排版 (A3 对折 / A4 订装), 标注考试时间/注意事项/答题卡样式, 线上模考需在 APP 内配置计时/交卷/自动判分功能"
  "考试组织: 线上模考 (如粉笔模考大赛, 每周六 9:00-11:00 行测 / 14:00-17:00 申论) 设固定开考时间 + 倒计时 + 到时自动收卷; 线下模考需安排考场/监考/收卷"
  "评分: 行测客观题由系统自动判分, 申论主观题由教师按采分点评分 (或 AI 初评 + 人工复核); 粉笔模考大赛 2025 年 44 季累计报名 878 万人次 (T03-S016)"
  "数据分析与报告: 生成个人成绩报告 (总分/排名/各模块得分/正确率/耗时分布) + 全场数据分析 (平均分/各题正确率/区分度/难度系数), 输出「考情分析简报」指导后续教学"
  "解析直播: 考试当天或次日由名师直播逐题解析, 重点讲高错率题和新题型, 引导学员购买后续课程"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-5-walkthrough"
fi
