#!/usr/bin/env bash
# workflow-2.sh — 申论备考工作流 (材料阅读 → 要点提取 → 题型框架 → 大作文 → 时政积累) SOP walkthrough for 公务员考试培训.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="公务员考试培训"
WORKFLOW="申论备考工作流 (材料阅读 → 要点提取 → 题型框架 → 大作文 → 时政积累)"

usage() {
  cat <<EOF
workflow-2.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-2.sh             # interactive
  ./workflow-2.sh --dry-run
  ./workflow-2.sh --json
  ./workflow-2.sh --explain
  ./workflow-2.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "申论备考工作流 (材料阅读 → 要点提取 → 题型框架 → 大作文 → 时政积累)" 工作流。

入门 SOP 共 7 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "了解申论题型: 归纳概括 / 综合分析 / 提出对策 / 贯彻执行 (公文写作) / 大作文 (议论文), 国考分副省级卷 (5 题) 和地市级卷 (5 题) 和行政执法类卷 (5 题)"
  "材料阅读训练: 每篇材料 6000-8000 字, 训练「三遍读法」— 第一遍通读标注关键词 (2 分钟), 第二遍逐段提炼要点 (划出动词/转折词/总结句), 第三遍对应题目回找材料"
  "要点提取: 掌握「答案 90% 来自材料」原则 (三大机构共识), 学会识别材料中的观点句/对策句/原因句/影响句, 分条列出, 每条 20-30 字"
  "题型框架训练: 归纳概括 = 总括句 + 分条要点; 综合分析 = 是什么 + 为什么 + 怎么办; 提出对策 = 问题 + 原因 + 对策; 贯彻执行 = 格式 + 内容 (按文种套框架)"
  "大作文 (议论文): 结构 = 标题 + 开头 (引出论点) + 分论点 1-3 段 (每段: 分论点 + 论据 + 分析 + 回扣) + 结尾 (升华), 总字数 1000-1200 字, 训练 50 分钟内完成"
  "时政素材积累: 每天 15-20 分钟阅读半月谈/人民日报评论/学习强国, 按「经济/政治/文化/社会/生态」五位一体分类摘抄, 每个主题积累 3-5 个案例 + 2-3 句金句"
  "练笔节奏: 前期每周 1 篇大作文 + 2 套小题, 后期每周 2 篇大作文 + 3 套小题, 每篇写完找老师或 AI 批改, 对照评分标准逐项改进"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-2-walkthrough"
fi
