#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 健身私教 — 为客户设计、指导和推进个性化训练方案的专业工艺, 有别于团课教练、物理治疗师或运动队教练: (a) 训练方案设计与周期化 (线性 / 波动 / 板块周期化 Bompa & Haff; NSCA《力量训练与体能训练精要》行业圣经; Schoenfeld 肌肥大机制; Helms/Valdez/Morgan 肌肉与力量金字塔; 共轭训练法 Simmons/Westside; Starting Strength 线性渐进 Rippetoe; Renaissance Periodization 训练量地标 Israetel); (b) 动作评估与筛查 (FMS 功能性动作筛查 Gray Cook; NASM CEx 纠正性训练连续体 抑制-拉伸-激活-整合; 关节逐级方法 Cook/Boyle; 姿势与代偿模式识别; PAR-Q+ 与 ACSM 运动前筛查指南); (c) 教学与指令 (外部 vs 内部注意焦点 Wulf; 差异化学习 Schöllhorn; 约束导向方法 Davids/Renshaw; RIR/RPE 自动调节 Zourdos/Helms; 动机访谈在健身中的应用 Rollnick/Miller); (d) 营养指导的执业边界 (宏量营养素周期化; Precision Nutrition / ISSN 立场声明的循证建议; 边界: 私教提供一般性指导, 医学营养治疗需 RD/RDN 资质; 能量可用性与 RED-S Mountjoy IOC 共识); (e) 商业与客户管理 (客户留存与方案依从; 咨询与销售伦理; 线上教练平台与规模化 Goodman PTDC; 方案交付工具 TrueCoach/Trainerize/TrainHeroic; 课时定价模型; 独立教练 vs 健身房雇员); (f) 专项方向 (运动表现 CSCS; 纠正性训练 CES; 老年健身 SFN; 产前产后; 青少年 YSCA; 适应性 / 无障碍健身; 健美 / 形体; 力量举; 耐力运动 S&C)。诚实处理: 兄弟科学 vs 循证之争, 补剂行业利益冲突, 合成代谢激素使用现状 (诚实但不推广: 匿名调查约 30% 有经验男性健身者使用过 — 业内估, Kanayama/Pope/Hudson 记录健康风险, WADA 禁用清单用于竞技语境), 体型焦虑与进食障碍风险 (男性私教肌肉变形症, 正食症倾向, NEDA 负责任语言指南), 健身房掠夺性销售 (高压推销、误导性对比照、长约锁定), 执业边界违规 (私教诊断伤病或超范围开饮食处方), 线上教练认证造假 (周末速成、未经认可的认证)。不含: 物理治疗 / 康复治疗 (持照医疗职业), 不含: 团课教练 (Les Mills/Zumba/CrossFit 分馆教练 — 相邻但不同), 不含: 精英竞技运动教练 (团队项目周期化, 不同职业路径), 不含: 营养作为主业 (临床营养学需单独资质)。.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="健身私教 — 为客户设计、指导和推进个性化训练方案的专业工艺, 有别于团课教练、物理治疗师或运动队教练: (a) 训练方案设计与周期化 (线性 / 波动 / 板块周期化 Bompa & Haff; NSCA《力量训练与体能训练精要》行业圣经; Schoenfeld 肌肥大机制; Helms/Valdez/Morgan 肌肉与力量金字塔; 共轭训练法 Simmons/Westside; Starting Strength 线性渐进 Rippetoe; Renaissance Periodization 训练量地标 Israetel); (b) 动作评估与筛查 (FMS 功能性动作筛查 Gray Cook; NASM CEx 纠正性训练连续体 抑制-拉伸-激活-整合; 关节逐级方法 Cook/Boyle; 姿势与代偿模式识别; PAR-Q+ 与 ACSM 运动前筛查指南); (c) 教学与指令 (外部 vs 内部注意焦点 Wulf; 差异化学习 Schöllhorn; 约束导向方法 Davids/Renshaw; RIR/RPE 自动调节 Zourdos/Helms; 动机访谈在健身中的应用 Rollnick/Miller); (d) 营养指导的执业边界 (宏量营养素周期化; Precision Nutrition / ISSN 立场声明的循证建议; 边界: 私教提供一般性指导, 医学营养治疗需 RD/RDN 资质; 能量可用性与 RED-S Mountjoy IOC 共识); (e) 商业与客户管理 (客户留存与方案依从; 咨询与销售伦理; 线上教练平台与规模化 Goodman PTDC; 方案交付工具 TrueCoach/Trainerize/TrainHeroic; 课时定价模型; 独立教练 vs 健身房雇员); (f) 专项方向 (运动表现 CSCS; 纠正性训练 CES; 老年健身 SFN; 产前产后; 青少年 YSCA; 适应性 / 无障碍健身; 健美 / 形体; 力量举; 耐力运动 S&C)。诚实处理: 兄弟科学 vs 循证之争, 补剂行业利益冲突, 合成代谢激素使用现状 (诚实但不推广: 匿名调查约 30% 有经验男性健身者使用过 — 业内估, Kanayama/Pope/Hudson 记录健康风险, WADA 禁用清单用于竞技语境), 体型焦虑与进食障碍风险 (男性私教肌肉变形症, 正食症倾向, NEDA 负责任语言指南), 健身房掠夺性销售 (高压推销、误导性对比照、长约锁定), 执业边界违规 (私教诊断伤病或超范围开饮食处方), 线上教练认证造假 (周末速成、未经认可的认证)。不含: 物理治疗 / 康复治疗 (持照医疗职业), 不含: 团课教练 (Les Mills/Zumba/CrossFit 分馆教练 — 相邻但不同), 不含: 精英竞技运动教练 (团队项目周期化, 不同职业路径), 不含: 营养作为主业 (临床营养学需单独资质)。"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 客户画像评估
  9.2 动作能力基线
  9.3 训练方案匹配
  9.4 营养与恢复状态
  9.5 执业边界检查
  9.6 工具选型
  9.7 持续学习方向

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "客户画像评估"
  "动作能力基线"
  "训练方案匹配"
  "营养与恢复状态"
  "执业边界检查"
  "工具选型"
  "持续学习方向"
)
declare -a DIM_QUESTIONS=(
  "年龄、训练年限、伤病史、生活方式(久坐/活跃)、心理动机(外在/内在)"
  "FMS 评分、主要代偿模式(膝内扣/骨盆前倾/肩上举受限)、关节活动度"
  "客户目标 × 训练年限 → 适合的周期化模式、训练频率、动作选择"
  "当前饮食模式(是否达到蛋白质目标)、睡眠质量、生活压力水平"
  "客户的需求是否超出私教执业范围(需要医学诊断/临床营养/心理干预)"
  "当前客户量 × 服务形式(线下/线上/混合) × 预算 → 适合的平台和设备"
  "当前技能缺口(通过客户反馈和自我评估识别)+ 行业趋势(MASS/SBS/NSCA 会议)"
)
declare -a DIM_SOURCES=(
  ""
  ""
  ""
  ""
  ""
  ""
  ""
)
declare -a DIM_OUTPUT_FORMATS=(
  ""
  ""
  ""
  ""
  ""
  ""
  ""
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
