#!/usr/bin/env bash
# omo.sh — 线上线下混合教学 (OMO) SOP walkthrough for 银发教育.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="银发教育"
WORKFLOW="线上线下混合教学 (OMO)"

usage() {
  cat <<EOF
omo.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./omo.sh             # interactive
  ./omo.sh --dry-run
  ./omo.sh --json
  ./omo.sh --explain
  ./omo.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "线上线下混合教学 (OMO)" 工作流。

入门 SOP 共 1 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "确定混合教学课程(优先选择视觉演示性强的课型: 书法/绘画/健康讲座/太极/插花; 实操性强需面对面的暂不混合) 2. 搭建直播环境(教室安装固定高清摄像头对准讲台+黑板+示范区; 无线麦克风确保讲师走动时音质稳定; ≥100M带宽稳定上行; 推流至腾讯会议/钉钉/微信群直播/小鹅通/校内平台) 3. 线上学员注册与分流(注册线上班→获取直播链接+回放权限, 线上班额可放大5-10倍不受教室座位限制; 线上学费可低于线下以扩大覆盖) 4. 课前推送预习材料(微信群/APP推送教学大纲/预习PPT/2-3分钟预告短视频, 提前1天发送) 5. 同步授课(讲师线下面授同时开启直播; 助教负责管理直播间; 线上学员通过弹幕提问/连麦互动/打字留言, 讲师定时关注线上提问) 6. 课后回放+作业(录播视频24小时内上传平台, 学员可反复观看/倍速/暂停; 线上学员微信群提交作品照片/视频/练习截图) 7. 分层辅导(线下助教现场指导; 线上助教微信群图文答疑+语音点评; 每周设1次线上集中答疑时间) 8. 统一评估(线上线下学员使用相同考核标准, 学分等值认定; 线上出勤以观看时长≥70%为准)"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "omo-walkthrough"
fi
