#!/usr/bin/env bash
# workflow-9.sh — 老年大学创建与运营 SOP walkthrough for 银发教育.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="银发教育"
WORKFLOW="老年大学创建与运营"

usage() {
  cat <<EOF
workflow-9.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-9.sh             # interactive
  ./workflow-9.sh --dry-run
  ./workflow-9.sh --json
  ./workflow-9.sh --explain
  ./workflow-9.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "老年大学创建与运营" 工作流。

入门 SOP 共 1 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "确定举办主体与定位(政府办: 教育局/老干部局主导; 高校办: 依托开放大学/普通高校离退休处; 企业办: 养老企业/教育公司; 社会组织办: 基金会/协会; 明确服务区域半径和目标人群定位) 2. 可行性调研(区域60岁+人口数量及增长趋势/现有老年教育供给缺口/周边同类机构竞争分析/潜在场地选址≥3个备选/交通便利性评估) 3. 申请审批(向区/县教育行政部门提交: 办学方案/教学计划/师资名单/场地产权或租赁证明/资金来源说明/消防验收/卫生许可; 获取办学许可证; 社会力量办学还需民办教育许可) 4. 工商/税务登记(非营利性: 民政登记为社会服务机构; 营利性: 营业执照+税务登记证+发改委收费许可证) 5. 场地建设与适老化改造(无障碍通道/电梯/防滑地面/扶手/大字标识/充足照明/AED+急救药箱/监控; 教室≥30人容量; 严格符合建筑/消防/安全/卫生/环保/抗震国家和地方规范; 黑龙江办法要求办学场所相对独立完整) 6. 数字化基础设施(宽带网络/教学管理系统/选课报名平台/直播设备/投影/扩音, 黑龙江办法明确要求具备数字化基础设施) 7. 组建管理团队+招募首批师资(校长+教务主任+财务+后勤+安保; 首批开设3-5门受欢迎度最高的核心课程: 书法/声乐/太极/智能手机/健康养生) 8. 制定管理制度(学籍管理制度/招生细则/学员守则/安全预案/财务管理制度/志愿者管理制度/教师聘任制度; 黑龙江办法要求建立完善学籍管理、招生细则、学员守则) 9. 首期招生+试运营(首学期小规模开3-5个班验证模式, 广泛收集学员/讲师/社区反馈进行迭代) 10. 正式运营+持续扩容(逐年增加课程/班级/教学点; 满2年可申报中国老年大学协会示范校评估; 对接国家老年大学体系获取资源)"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-9-walkthrough"
fi
