#!/usr/bin/env bash
# workflow-5.sh — 教学质量评估 SOP walkthrough for 银发教育.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="银发教育"
WORKFLOW="教学质量评估"

usage() {
  cat <<EOF
workflow-5.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-5.sh             # interactive
  ./workflow-5.sh --dry-run
  ./workflow-5.sh --json
  ./workflow-5.sh --explain
  ./workflow-5.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "教学质量评估" 工作流。

入门 SOP 共 1 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "制定评估指标体系(六维度: 教师教学水平/教学方法/教学效果/教学态度/学员学习质量/教学管理质量; 参照T/ZLDX 001-2021示范校评价指南设定权重) 2. 过程数据采集(每周: 出勤率统计; 每月: 教学督导随机巡查1-2次; 每节课: 讲师填写教学日志; 实时: 学员投诉/表扬记录) 3. 学期中期学员满意度调查(纸质/微信二维码问卷, 覆盖率≥80%有效样本, 含教学内容/讲师/环境/管理四大板块) 4. 教学成果评审(书法/绘画/摄影等实操课以作品展评+进步幅度; 理论课以开卷结业考试/小论文/口头汇报) 5. 学期末综合评教(学员评分占40%+同行互评占30%+教学督导评分占30%, 三方加权计算) 6. 学分认定(按课时数+出勤率≥80%+成绩达标三条件综合认定, 录入国家学分银行/省级学分银行) 7. 评估结果反馈(优秀讲师公开表彰/优先续聘/推荐入中央机关老年大学师资库; 低分讲师约谈/培训辅导/调整课程/连续不合格解聘) 8. 年度教学质量报告(汇总全年数据编制报告, 含改进计划, 上报教育主管部门+老年大学协会)"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-5-walkthrough"
fi
