#!/usr/bin/env bash
# workflow-8.sh — 师资培训与管理 SOP walkthrough for 银发教育.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="银发教育"
WORKFLOW="师资培训与管理"

usage() {
  cat <<EOF
workflow-8.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-8.sh             # interactive
  ./workflow-8.sh --dry-run
  ./workflow-8.sh --json
  ./workflow-8.sh --explain
  ./workflow-8.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "师资培训与管理" 工作流。

入门 SOP 共 1 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "师资需求盘点(依据下学期课程计划, 确定各科目讲师缺口数量, 按专职/兼职/志愿者三类分别统计; 同时梳理现有讲师续聘意愿) 2. 多渠道招募(第一优先: 退休教师/高校教授/中小学退休名师; 第二: 行业专家/非遗传承人/资深从业者; 第三: 社会志愿者/大学生; 第四: 优秀学员\"能者为师\"; 渠道: 官网公告/社区张贴/老干部局推荐/人才市场/教育系统内部推荐/国家老年大学能者为师库) 3. 资质审核(核验学历/专业背景/教学经验/健康状况; 黑龙江办法规定校长须大专以上学历+3年教育管理经验; 讲师须具备相关领域中级以上职称或同等能力证明) 4. 岗前培训(2-3天集中培训: 老年教育学基础/老年学习者心理特点/适老化教学技巧/课堂安全应急处理/信息化工具使用/教学设备操作; 山东省要求逐步实行持证上岗) 5. 试讲考核(教学委员会+学员代表10-15人组成评审组听课打分; 评分维度: 教学内容/表达清晰度/互动能力/适老化程度; 通过后正式聘任) 6. 签订聘书/协议(明确课时费标准/教学内容要求/课时量/考核指标/保密条款, 通常按学期或学年续聘; 志愿者签志愿服务协议含保险) 7. 在职培训与发展(每学期至少1次集中教研活动/跨校经验交流/示范课观摩; 优秀讲师入选中央机关老年大学师资库/国家老年大学师资共享库, 可参加全国性研修培训) 8. 年度考核与退出(结合学员评教分数+出勤率+教学成果+教研参与度综合评定; 优秀者表彰+提高课时费; 连续两学期不合格约谈→调整→解聘; 志愿者可随时退出但需提前告知)"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-8-walkthrough"
fi
