#!/usr/bin/env bash
# workflow-7.sh — 送教上门 / 送教下乡 SOP walkthrough for 银发教育.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="银发教育"
WORKFLOW="送教上门 / 送教下乡"

usage() {
  cat <<EOF
workflow-7.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./workflow-7.sh             # interactive
  ./workflow-7.sh --dry-run
  ./workflow-7.sh --json
  ./workflow-7.sh --explain
  ./workflow-7.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "送教上门 / 送教下乡" 工作流。

入门 SOP 共 1 步, 失败模式自检 0 项。

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "摸排服务对象(社区网格员/村委会排查辖区内行动不便/居住偏远/交通不便的老年人, 建立需求台账: 姓名/年龄/身体状况/学习意愿/可达方式) 2. 确定送教形式(入户一对一/社区活动室集中授课10-20人/乡村教学点固定班/流动课堂巡回教学, 根据服务对象分布密度选择) 3. 组建送教团队(志愿讲师+社工+社区工作者+驻村干部, 配备便携教具/移动投影仪/蓝牙音箱/大字教材/急救药箱) 4. 制定送教课表(每月1-2次, 每次1-2课时; 课程以健康管理/防诈骗/手机使用/法律权益/生活安全为主, 与老人日常痛点直接相关) 5. 现场教学(到社区活动室/村委会议室/养老院活动厅/日间照料中心/老人家中; 适老化教学节奏: 慢讲/多重复/互动多/实物演示/方言教学) 6. 分发学习材料(大字版A4纸质资料/操作步骤卡片/带二维码可扫看录播视频的卡片, 方便课后自主复习) 7. 建立跟踪回访机制(下次送教时先复习上次内容检验效果; 建微信群或电话定期联络; 有需求随时响应) 8. 汇总送教记录并上报(含覆盖人数/课时数/课程内容/满意度/照片存档, 纳入社区教育年度考核指标)"
)
declare -a FAILURE_MODES=(

)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "workflow-7-walkthrough"
fi
