#!/usr/bin/env bash
# implant.sh — Implant 决策助手 for 口腔种植 (含 单牙/多牙缺失种植 / 全口 All-on-X / 即刻种植 即刻负重 / 上颌窦提升 / 牙槽嵴骨增量 GBR / 软组织移植 / 数字化种植 (CBCT 设计 + 口扫 + 导板 + CAD-CAM 上部) / 种植体周炎防治 / 种植修复 (基台 + 冠 + 杆卡 + 覆盖义齿) — 不含 普通牙体牙髓 / 正畸 / 儿牙 / 口腔颌面外科肿瘤 / 隐形矫治商业).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="口腔种植 (含 单牙/多牙缺失种植 / 全口 All-on-X / 即刻种植 即刻负重 / 上颌窦提升 / 牙槽嵴骨增量 GBR / 软组织移植 / 数字化种植 (CBCT 设计 + 口扫 + 导板 + CAD-CAM 上部) / 种植体周炎防治 / 种植修复 (基台 + 冠 + 杆卡 + 覆盖义齿) — 不含 普通牙体牙髓 / 正畸 / 儿牙 / 口腔颌面外科肿瘤 / 隐形矫治商业)"
TOPIC="Implant"

usage() {
  cat <<EOF
implant.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 4 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./implant.sh             # interactive
  ./implant.sh --dry-run   # walk through but no file
  ./implant.sh --json      # JSON to stdout
  ./implant.sh --explain   # show backing playbook rules + mental models
  ./implant.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 Implant 主题下的 playbook 规则组合成交互树。

基于 4 条规则:
  • 如果 上颌后牙残余骨高度 < 5mm → 则 : 上颌窦提升 lateral approach **分期** (植骨先 + 4-6 月 maturation + 二期
  • 如果 牙槽嵴宽度 < 5mm (Buser 5mm rule) → 则 : 横向骨增量 + 二期 implant, 不做窄径 implant 替代骨增量; 即使 3.0-3.3mm 窄 imp
  • 如果 种植体周炎 BoP+ + PPD ≥ 6mm + 骨吸收 ≥ 2mm → 则 : 启动 EFP S3-guideline 阶梯治疗 — 先 nonsurgical (mechanical debri
  • 如果 AI / CBCT 自动分割 / planning 工具 给出 implant 位置建议 → 则 : 拿来当 第二意见, **绝不直接采纳**; 必须人 verify 神经走向 + 骨密度 + 修复反推合理性 + bi

相关心智模型:
  • 骨结合 (osseointegration) 是时间 × 生物学 × 机械 三轴函数, 不是单一植入操作: Brånemark 1969 发现 osseointegration 时已确认: 不是钛把骨"咬住", 是骨细胞主动长到钛表面光滑层 — 需要 8-12 周 (业内估, 视骨密度 D1-D4 区间) 
  • 长期成功 = 骨 + 软组织 + 修复 三角, 缺一不可 (Lindhe-Berglundh 整合学派): Lindhe 自 1970s 起把 牙周 与 种植 视为同一生物学连续体 (clinical periodontology AND implant dentistry 同一本教科书 7 版). 临床长

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "上颌后牙残余骨高度 < 5mm"
  "牙槽嵴宽度 < 5mm (Buser 5mm rule)"
  "种植体周炎 BoP+ + PPD ≥ 6mm + 骨吸收 ≥ 2mm"
  "AI / CBCT 自动分割 / planning 工具 给出 implant 位置建议"
)
declare -a RULE_ACTIONS=(
  ": 上颌窦提升 lateral approach **分期** (植骨先 + 4-6 月 maturation + 二期 implant), 不同期; 4-5mm 区间是边界, ≤ 4mm 必须分期"
  ": 横向骨增量 + 二期 implant, 不做窄径 implant 替代骨增量; 即使 3.0-3.3mm 窄 implant 长期 crown-root ratio 不利, 不解决根本问题"
  ": 启动 EFP S3-guideline 阶梯治疗 — 先 nonsurgical (mechanical debridement + AIRFLOW + 局部 抗菌); 1-3 月 reassess; 不愈则 surgical (resective / regenerative / explantation); **不要直接拔 implant 而不评估**"
  ": 拿来当 第二意见, **绝不直接采纳**; 必须人 verify 神经走向 + 骨密度 + 修复反推合理性 + biotype + 微笑线; AI 工具 (Diagnocat / Denti.AI / DTX Studio 2.0 / 3Shape AI) 当前 hype 高点, 落地 RCT 仍稀少 (业内估 2024-2025 仅 单中心初步报告 < 10 篇), 6-12 月以上 weight 慎重"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "implant-decision"
fi
