#!/usr/bin/env bash
# topic-3.sh — 种植 决策助手 for 口腔种植 (含 单牙/多牙缺失种植 / 全口 All-on-X / 即刻种植 即刻负重 / 上颌窦提升 / 牙槽嵴骨增量 GBR / 软组织移植 / 数字化种植 (CBCT 设计 + 口扫 + 导板 + CAD-CAM 上部) / 种植体周炎防治 / 种植修复 (基台 + 冠 + 杆卡 + 覆盖义齿) — 不含 普通牙体牙髓 / 正畸 / 儿牙 / 口腔颌面外科肿瘤 / 隐形矫治商业).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="口腔种植 (含 单牙/多牙缺失种植 / 全口 All-on-X / 即刻种植 即刻负重 / 上颌窦提升 / 牙槽嵴骨增量 GBR / 软组织移植 / 数字化种植 (CBCT 设计 + 口扫 + 导板 + CAD-CAM 上部) / 种植体周炎防治 / 种植修复 (基台 + 冠 + 杆卡 + 覆盖义齿) — 不含 普通牙体牙髓 / 正畸 / 儿牙 / 口腔颌面外科肿瘤 / 隐形矫治商业)"
TOPIC="种植"

usage() {
  cat <<EOF
topic-3.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 1 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-3.sh             # interactive
  ./topic-3.sh --dry-run   # walk through but no file
  ./topic-3.sh --json      # JSON to stdout
  ./topic-3.sh --explain   # show backing playbook rules + mental models
  ./topic-3.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 种植 主题下的 playbook 规则组合成交互树。

基于 1 条规则:
  • 如果 HbA1c > 8.0% 或 吸烟 > 10 支/日 或 双膦酸盐 IV 史 ≥ 6 月 → 则 : 推迟种植 / 转诊 endocrinologist + 戒烟门诊; 不在控糖差 / 重度吸烟 / 高 BRONJ 风

相关心智模型:
  • 骨结合 (osseointegration) 是时间 × 生物学 × 机械 三轴函数, 不是单一植入操作: Brånemark 1969 发现 osseointegration 时已确认: 不是钛把骨"咬住", 是骨细胞主动长到钛表面光滑层 — 需要 8-12 周 (业内估, 视骨密度 D1-D4 区间) 
  • 长期成功 = 骨 + 软组织 + 修复 三角, 缺一不可 (Lindhe-Berglundh 整合学派): Lindhe 自 1970s 起把 牙周 与 种植 视为同一生物学连续体 (clinical periodontology AND implant dentistry 同一本教科书 7 版). 临床长

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "HbA1c > 8.0% 或 吸烟 > 10 支/日 或 双膦酸盐 IV 史 ≥ 6 月"
)
declare -a RULE_ACTIONS=(
  ": 推迟种植 / 转诊 endocrinologist + 戒烟门诊; 不在控糖差 / 重度吸烟 / 高 BRONJ 风险时直接植入"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-3-decision"
fi
