#!/usr/bin/env bash
# topic-2.sh — 业内 决策助手 for 独立开发者与微型 SaaS — 单人或极小团队 (≤3 人) 构建可持续订阅收入的软件产品商业, 有别于自由职业/咨询、企业级 SaaS 和开源维护: (a) 产品发现与验证 (自己的痒 vs 市场优先 Nugent/Walling; 着陆页冒烟测试; 先接 Stripe 再写代码; JTBD 访谈适配独立开发者场景; Reddit/HN/X/社区痛点挖掘; Mom Test 验证框架; 公开构建作为验证机制); (b) 独立开发者技术架构 (无聊技术论 McKinley; 单体优先; serverless vs VPS 在 ≤$100/月预算下的取舍; Rails/Django/Laravel/Next.js 等框架的出货速度选型; 托管服务优先于自建; Supabase/PlanetScale/Neon 数据库即服务; Clerk/Auth0 认证即服务; Stripe/Paddle/LemonSqueezy 支付; Vercel/Fly.io/Railway 部署; AI 辅助编码 Cursor/Copilot 作为力量倍增器); (c) 无营销团队的分发与增长 (SEO 作为微型 SaaS 护城河; Product Hunt 发布; AppSumo 终身授权利弊; 冷邮件; Twitter/X 公开构建; IndieHackers 社区分发; 集成市场 Shopify/WordPress/Zapier/Slack 应用目录; 联盟计划; 一人内容营销); (d) 定价与变现 (SaaS 定价心理学; freemium vs 免费试用 vs 纯付费; 按席位 vs 按用量 vs 固定费率; 年付折扣; 老用户保价; 微型 SaaS 流失率控制; MRR/ARR/LTV/CAC 在微型规模的含义; $10K MRR 里程碑心理学); (e) 独立创始人心智模型与生活设计 (default alive vs default dead Graham; 拉面盈利 Levels; 生活方式生意 vs 增长生意的光谱; 独立开发者倦怠预防; 时间管理与上下文切换成本; 地理套利与远程优先; 一次构建反复销售的资产思维; 社区作为支持网络 IndieHackers/WIP/MicroConf); (f) 法务与运营基础 (公司注册地选择 LLC/Ltd/GmbH 税效; Stripe Atlas vs Firstbase vs 本地律师; 服务条款与隐私政策; GDPR/CCPA 低成本合规; 知识产权基础; 首次雇人的承包商 vs 员工选择; 独立开发者会计 SaaS — Xero/QuickBooks; 多辖区税务义务)。中国独立开发者生态: 出海作为主导策略 (从中国构建面向全球市场的产品以避开国内竞争/监管); 即刻/V2EX/少数派作为社区枢纽; 微信小程序作为替代分发; 小报童/爱发电作为中文市场变现; 人民币定价心理学; 支付宝/微信支付集成; ICP 备案要求; 中国区 App Store 审核差异; 独立开发者周刊。诚实处理: 生存偏差 (每一个 Pieter Levels 背后是数千个从未达到 $1K MRR 的人), AI 对微型 SaaS 生态位的颠覆 (wrapper 产品脆弱), 独自构建的孤独与心理健康成本, 公开构建的表演性质 vs 真正透明, AppSumo 终身授权上瘾毁坏单位经济, 样板代码销售的伦理边界。不含: 企业级 SaaS (不同 GTM/销售/融资模型), 不含: 自由职业/咨询 (用时间换钱非建资产), 不含: 开源维护 (不同可持续性模型), 不含: 风投支持的创业 (不同增长期望), 不含: 无代码/低代码平台构建 (相邻但不同受众), 不含: 内容创作作为主业。.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="独立开发者与微型 SaaS — 单人或极小团队 (≤3 人) 构建可持续订阅收入的软件产品商业, 有别于自由职业/咨询、企业级 SaaS 和开源维护: (a) 产品发现与验证 (自己的痒 vs 市场优先 Nugent/Walling; 着陆页冒烟测试; 先接 Stripe 再写代码; JTBD 访谈适配独立开发者场景; Reddit/HN/X/社区痛点挖掘; Mom Test 验证框架; 公开构建作为验证机制); (b) 独立开发者技术架构 (无聊技术论 McKinley; 单体优先; serverless vs VPS 在 ≤$100/月预算下的取舍; Rails/Django/Laravel/Next.js 等框架的出货速度选型; 托管服务优先于自建; Supabase/PlanetScale/Neon 数据库即服务; Clerk/Auth0 认证即服务; Stripe/Paddle/LemonSqueezy 支付; Vercel/Fly.io/Railway 部署; AI 辅助编码 Cursor/Copilot 作为力量倍增器); (c) 无营销团队的分发与增长 (SEO 作为微型 SaaS 护城河; Product Hunt 发布; AppSumo 终身授权利弊; 冷邮件; Twitter/X 公开构建; IndieHackers 社区分发; 集成市场 Shopify/WordPress/Zapier/Slack 应用目录; 联盟计划; 一人内容营销); (d) 定价与变现 (SaaS 定价心理学; freemium vs 免费试用 vs 纯付费; 按席位 vs 按用量 vs 固定费率; 年付折扣; 老用户保价; 微型 SaaS 流失率控制; MRR/ARR/LTV/CAC 在微型规模的含义; $10K MRR 里程碑心理学); (e) 独立创始人心智模型与生活设计 (default alive vs default dead Graham; 拉面盈利 Levels; 生活方式生意 vs 增长生意的光谱; 独立开发者倦怠预防; 时间管理与上下文切换成本; 地理套利与远程优先; 一次构建反复销售的资产思维; 社区作为支持网络 IndieHackers/WIP/MicroConf); (f) 法务与运营基础 (公司注册地选择 LLC/Ltd/GmbH 税效; Stripe Atlas vs Firstbase vs 本地律师; 服务条款与隐私政策; GDPR/CCPA 低成本合规; 知识产权基础; 首次雇人的承包商 vs 员工选择; 独立开发者会计 SaaS — Xero/QuickBooks; 多辖区税务义务)。中国独立开发者生态: 出海作为主导策略 (从中国构建面向全球市场的产品以避开国内竞争/监管); 即刻/V2EX/少数派作为社区枢纽; 微信小程序作为替代分发; 小报童/爱发电作为中文市场变现; 人民币定价心理学; 支付宝/微信支付集成; ICP 备案要求; 中国区 App Store 审核差异; 独立开发者周刊。诚实处理: 生存偏差 (每一个 Pieter Levels 背后是数千个从未达到 $1K MRR 的人), AI 对微型 SaaS 生态位的颠覆 (wrapper 产品脆弱), 独自构建的孤独与心理健康成本, 公开构建的表演性质 vs 真正透明, AppSumo 终身授权上瘾毁坏单位经济, 样板代码销售的伦理边界。不含: 企业级 SaaS (不同 GTM/销售/融资模型), 不含: 自由职业/咨询 (用时间换钱非建资产), 不含: 开源维护 (不同可持续性模型), 不含: 风投支持的创业 (不同增长期望), 不含: 无代码/低代码平台构建 (相邻但不同受众), 不含: 内容创作作为主业。"
TOPIC="业内"

usage() {
  cat <<EOF
topic-2.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 2 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-2.sh             # interactive
  ./topic-2.sh --dry-run   # walk through but no file
  ./topic-2.sh --json      # JSON to stdout
  ./topic-2.sh --explain   # show backing playbook rules + mental models
  ./topic-2.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 业内 主题下的 playbook 规则组合成交互树。

基于 2 条规则:
  • 如果 你在纠结定价 → 则 : 起价定在你觉得舒适的价格的约 2 倍 (业内估)。$29/月比 $9/月对独立开发者更可持续 — 前者约 350 客
  • 如果 你考虑 AppSumo LTD → 则 : 仅在以下全部满足时才做 — (a) 产品已稳定, 不需要频繁迭代; (b) 服务成本极低 (约 $5/年/用户以下,

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "你在纠结定价"
  "你考虑 AppSumo LTD"
)
declare -a RULE_ACTIONS=(
  ": 起价定在你觉得舒适的价格的约 2 倍 (业内估)。\$29/月比 \$9/月对独立开发者更可持续 — 前者约 350 客户达 \$10K MRR, 后者需约 1100 (T04-S010, T04-S023)"
  ": 仅在以下全部满足时才做 — (a) 产品已稳定, 不需要频繁迭代; (b) 服务成本极低 (约 \$5/年/用户以下, 业内估); (c) 你明确把 LTD 当一次性现金注入而非增长策略。案例: 多名 MicroConf 创始人公开表示 LTD 是最大战略失误 — 终身客户 \$0 MRR 但占用约 30% 支持资源 (业内估, T04-S021)"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-2-decision"
fi
