#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for 口腔种植 (含 单牙/多牙缺失种植 / 全口 All-on-X / 即刻种植 即刻负重 / 上颌窦提升 / 牙槽嵴骨增量 GBR / 软组织移植 / 数字化种植 (CBCT 设计 + 口扫 + 导板 + CAD-CAM 上部) / 种植体周炎防治 / 种植修复 (基台 + 冠 + 杆卡 + 覆盖义齿) — 不含 普通牙体牙髓 / 正畸 / 儿牙 / 口腔颌面外科肿瘤 / 隐形矫治商业).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="口腔种植 (含 单牙/多牙缺失种植 / 全口 All-on-X / 即刻种植 即刻负重 / 上颌窦提升 / 牙槽嵴骨增量 GBR / 软组织移植 / 数字化种植 (CBCT 设计 + 口扫 + 导板 + CAD-CAM 上部) / 种植体周炎防治 / 种植修复 (基台 + 冠 + 杆卡 + 覆盖义齿) — 不含 普通牙体牙髓 / 正畸 / 儿牙 / 口腔颌面外科肿瘤 / 隐形矫治商业)"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 Case 复杂度评估 (SAC + 风险分层)
  9.2 Restoration-driven planning (反推 implant 位置)
  9.3 软组织 + 硬组织 + 修复 三角对齐
  9.4 选型决策树 (vendor + system + 表面 + connection)
  9.5 长期 outcome 数据 + Cochrane SR 立场
  9.6 监管 + 医疗纠纷 防范 (medico-legal)
  9.7 长期维护 + 患者教育闭环

背后的心智模型:
  • 骨结合 (osseointegration) 是时间 × 生物学 × 机械 三轴函数, 不是单一植入操作: Brånemark 1969 发现 osseointegration 时已确认: 不是钛把骨"咬住", 是骨细胞主动长到钛表面光滑层 — 需要 8-12 周 (业内估, 视骨密度 D1-D4 区间) 
  • 长期成功 = 骨 + 软组织 + 修复 三角, 缺一不可 (Lindhe-Berglundh 整合学派): Lindhe 自 1970s 起把 牙周 与 种植 视为同一生物学连续体 (clinical periodontology AND implant dentistry 同一本教科书 7 版). 临床长
  • Restoration-driven implant placement — 拔牙后先决定修复目标, 反推种植位置 / 角度 (Salama 学派): Maurice Salama 与 DentalXP 学派核心: implant 位置 / 角度 / 深度 不是由 骨量 最大化 决定, 是由 最终修复体 (cement vs screw retain

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "Case 复杂度评估 (SAC + 风险分层)"
  "Restoration-driven planning (反推 implant 位置)"
  "软组织 + 硬组织 + 修复 三角对齐"
  "选型决策树 (vendor + system + 表面 + connection)"
  "长期 outcome 数据 + Cochrane SR 立场"
  "监管 + 医疗纠纷 防范 (medico-legal)"
  "长期维护 + 患者教育闭环"
)
declare -a DIM_QUESTIONS=(
  ""
  ""
  ""
  ""
  ""
  ""
  ""
)
declare -a DIM_SOURCES=(
  ""
  ""
  ""
  ""
  ""
  ""
  ""
)
declare -a DIM_OUTPUT_FORMATS=(
  ""
  ""
  ""
  ""
  ""
  ""
  ""
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
