#!/usr/bin/env bash
# agentic.sh — Agentic Protocol CLI for CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 9.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。"
DIM_COUNT=7

usage() {
  cat <<EOF
agentic.sh — Agentic Protocol CLI for ${INDUSTRY}

拿到 ${INDUSTRY} 行业的新问题时，按 ${DIM_COUNT} 个研究维度做功课再答。
不直接给答案，而是引导你用资深从业者的研究维度收集信息。

USAGE:
  ./agentic.sh                # interactive walkthrough
  ./agentic.sh --dry-run      # walk through but skip file write
  ./agentic.sh --json         # emit JSON to stdout
  ./agentic.sh --explain      # show backing mental models + sources
  ./agentic.sh --help         # this message
EOF
}

explain() {
  cat <<'EOT'
这个 Agentic Protocol 把这一行人面对新问题的研究维度结构化。

研究维度 (7 个):
  9.1 战略与定位语境 (Strategy & Positioning Context)
  9.2 资本配置基线 (Capital Allocation Baseline)
  9.3 高管班子健康度 (SLT Health & Talent Density)
  9.4 决策结构与节奏 (Decision Structure & Cadence)
  9.5 长期 invariants 与 bets 平衡 (Invariants vs Bets Balance)
  9.6 文化与 mistakes 浮现机制 (Culture & Surface-Mistakes Mechanism)
  9.7 治理与利益相关者 (Governance & Stakeholder Map)

背后的心智模型:
  • 资本配置 = CEO 最高杠杆工作 (Capital Allocation as the #1 Job): 「CEO 一辈子要做的几十个决策中, 资本配置 (5 levers: 内部再投 / 并购 / 派息 / 回购 / 还债) 的复利结果决定企业 20 年后的市值排序; 不算 hurdle rate / 
  • 战略转折点 + 主动 paranoia (Strategic Inflection Point + Paranoia as Discipline): 「10x 力 (技术 / 竞争 / 监管 / 用户行为) 改变行业基本面时, CEO 必须最先识别 + 主动毁掉一部分老业务穿越 SIP (Intel 1985 退 DRAM / 任正非 1998 华
  • 写作 = 思考 + 文件 / 仪式 / 节奏是 CEO 最高杠杆工具 (Writing is Thinking; Documents / Rituals / Cadence > SaaS): 「CEO 最高杠杆的工具不是任何 SaaS, 是 5 件「文件 / 仪式 / 节奏」: 致股东信 + WBR + 1:1 + Town Hall + 6-pager; 不能用 narrative 写清

来源: synthesis.md Section 9 + Section 1.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a DIM_TITLES=(
  "战略与定位语境 (Strategy & Positioning Context)"
  "资本配置基线 (Capital Allocation Baseline)"
  "高管班子健康度 (SLT Health & Talent Density)"
  "决策结构与节奏 (Decision Structure & Cadence)"
  "长期 invariants 与 bets 平衡 (Invariants vs Bets Balance)"
  "文化与 mistakes 浮现机制 (Culture & Surface-Mistakes Mechanism)"
  "治理与利益相关者 (Governance & Stakeholder Map)"
)
declare -a DIM_QUESTIONS=(
  "公司当前 stage (0→1 / 1→100 / mature / turnaround); 行业结构 (5 forces 当前状态); own 7 Powers 哪几条成立; 是否处于 SIP (10x 力 + 客户行为转向 + 一线吐槽)."
  "当前 5 levers 金额分布; own hurdle rate; 近 3 年同类公司 capital allocation 决策 outcomes; own free cash flow 与 invariants 一致性."
  "SLT 平均任期; keeper test 通过率; brilliant jerk 在 SLT 比例; 文化抗拒者在 SLT 比例; A-player 比例; SLT 1:1 cadence + content quality."
  "近 12 月 Type 1 决策数量 (应 ≤ 5, 业内估 Bezos / Mulally / Nadella 范式 T04-S053 T04-S035 T04-S012); 每个 Type 1 是否有 6-pager + premortem + post-mortem; SLT 是否真 Disagree and Commit (沉默反对率); WBR red/yellow 比例约 10% 以上 (业内估)."
  "own 公司 5-10 invariants 是否 explicit + 5 年内变化率约 20% 以内 (业内估, Bezos / Buffett letters 范式 T04-S055 T04-S073); 当前 active bets 列表 + 风险分布; 致股东信 invariants 段是否 anchor 投资人."
  "文化文档 (Culture Memo / LP / 心声社区) 是否 explicit + 持续重申; 文化抗拒者 fire 比例; mistakes 公开机制 (致股东信 mistakes 段 / WBR red / 心声社区匿名); psychological safety 信号 (员工敢说 bad news 比例)."
  "board composition (Lead Director / Audit Chair / Comp Chair 独立性); board off-site 频率 + 质量; 维权 surveillance (13D/13F monitor); shareholder primacy vs stakeholder capitalism own 立场 + ESG 披露义务 (按地); 是否有 activist 信号."
)
declare -a DIM_SOURCES=(
  "致股东信近 5 年 invariants 段; 行业分析 (Stratechery / Acquired); 客户访谈 ≥ 10 次; 一线员工 skip-level 1:1."
  "10-K + 财报 + Buffett / Bezos / Mark Leonard 致股东信; Mauboussin hurdle rate 框架; comparable companies database."
  "SLT 季度 360 + 外部 Spencer Stuart / Korn Ferry assessment; 自我观察 SLT 1:1; 跨级 skip-level 1:1; employee engagement (Lattice / Culture Amp / 心声社区)."
  "decision journal 近 12 月; WBR red/yellow 历史; SLT 1:1 中 disagreement 频率; post-mortem 文档."
  "历年致股东信 invariants 段对比; bets 内部 OKR + 资本配置历史; bets 失败的公开复盘 (透明度)."
  "文化文档版本史; fire 数据 + cause 分类; 致股东信 mistakes 段; 内部匿名渠道 + CEO 真去 read 记录."
  "proxy filing (DEF 14A); board pack 历史; Lead Director 月度 1:1; ISS / Glass Lewis engagement; 13D/13F filing monitor."
)
declare -a DIM_OUTPUT_FORMATS=(
  "1-page 战略 (winning aspiration → where to play → how to win → capabilities → mgmt systems) + 列出哪 1-2 Power 是 own moat + 列出 ≥ 1 个潜在 SIP 信号."
  "5 levers 当前分布表 + own hurdle rate 测算 + 列出近 12 月 ≥ \$X 的资本配置 thesis + 下一 24 月预期分布建议."
  "SLT 健康度 scorecard (talent density / culture fit / 任期分布 / keeper test 通过率) + 列出未来 3 月需 hire 的关键岗位 + 列出可能需要 transition 的高管."
  "决策结构 audit (Type 1 数量 / 6-pager 比例 / premortem 覆盖率 / WBR red transparency) + 列出 3 个最近 Type 1 决策的执行健康度."
  "invariants 列表 (5-10 条) + bets 当前 active 表 (含 Type 1/2 标注 + reversibility) + 致股东信对应段建议."
  "文化健康度 audit (文化抗拒者 fire 率 / mistakes 公开质量 / psychological safety 信号) + 列出 3 个最近 公开 mistakes 案例."
  "治理 audit (board composition + activist signal + ESG 披露状态) + 列出 next 12 月预期的治理变动 (e.g. director election / proxy / activist 风险)."
)
declare -a DIM_FINDINGS=()

if [[ $JSON -eq 0 ]]; then
  ms_section "${INDUSTRY} · Agentic Protocol"
  ms_info "拿到的问题是什么? (输入完后，敲一个空行结束)"
  echo
fi

PROBLEM="$(ms_read_multiline)"
ms_buffer_append "# ${INDUSTRY} — Agentic Protocol Report"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 问题"
ms_buffer_append ""
ms_buffer_append "$PROBLEM"
ms_buffer_append ""

for i in "${!DIM_TITLES[@]}"; do
  if [[ $JSON -eq 0 ]]; then
    ms_section "${DIM_TITLES[$i]}"
    echo "看什么:    ${DIM_QUESTIONS[$i]}"
    echo "在哪看:    ${DIM_SOURCES[$i]}"
    echo "输出格式:  ${DIM_OUTPUT_FORMATS[$i]}"
    echo
    ms_prompt "你的发现 / 推断 (空行结束):"
    echo
  fi
  finding="$(ms_read_multiline)"
  DIM_FINDINGS+=("$finding")

  ms_buffer_append "## ${DIM_TITLES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**看什么**: ${DIM_QUESTIONS[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**在哪看**: ${DIM_SOURCES[$i]}"
  ms_buffer_append ""
  ms_buffer_append "**发现**:"
  ms_buffer_append ""
  ms_buffer_append "$finding"
  ms_buffer_append ""
done

if [[ $JSON -eq 1 ]]; then
  args=("problem" "$PROBLEM")
  for i in "${!DIM_TITLES[@]}"; do
    args+=("dim_${i}_title" "${DIM_TITLES[$i]}")
    args+=("dim_${i}_finding" "${DIM_FINDINGS[$i]}")
  done
  ms_emit_json "${args[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "agentic-protocol"
fi
