#!/usr/bin/env bash
# topic-2.sh — 训练 决策助手 for 健身私教 — 为客户设计、指导和推进个性化训练方案的专业工艺, 有别于团课教练、物理治疗师或运动队教练: (a) 训练方案设计与周期化 (线性 / 波动 / 板块周期化 Bompa & Haff; NSCA《力量训练与体能训练精要》行业圣经; Schoenfeld 肌肥大机制; Helms/Valdez/Morgan 肌肉与力量金字塔; 共轭训练法 Simmons/Westside; Starting Strength 线性渐进 Rippetoe; Renaissance Periodization 训练量地标 Israetel); (b) 动作评估与筛查 (FMS 功能性动作筛查 Gray Cook; NASM CEx 纠正性训练连续体 抑制-拉伸-激活-整合; 关节逐级方法 Cook/Boyle; 姿势与代偿模式识别; PAR-Q+ 与 ACSM 运动前筛查指南); (c) 教学与指令 (外部 vs 内部注意焦点 Wulf; 差异化学习 Schöllhorn; 约束导向方法 Davids/Renshaw; RIR/RPE 自动调节 Zourdos/Helms; 动机访谈在健身中的应用 Rollnick/Miller); (d) 营养指导的执业边界 (宏量营养素周期化; Precision Nutrition / ISSN 立场声明的循证建议; 边界: 私教提供一般性指导, 医学营养治疗需 RD/RDN 资质; 能量可用性与 RED-S Mountjoy IOC 共识); (e) 商业与客户管理 (客户留存与方案依从; 咨询与销售伦理; 线上教练平台与规模化 Goodman PTDC; 方案交付工具 TrueCoach/Trainerize/TrainHeroic; 课时定价模型; 独立教练 vs 健身房雇员); (f) 专项方向 (运动表现 CSCS; 纠正性训练 CES; 老年健身 SFN; 产前产后; 青少年 YSCA; 适应性 / 无障碍健身; 健美 / 形体; 力量举; 耐力运动 S&C)。诚实处理: 兄弟科学 vs 循证之争, 补剂行业利益冲突, 合成代谢激素使用现状 (诚实但不推广: 匿名调查约 30% 有经验男性健身者使用过 — 业内估, Kanayama/Pope/Hudson 记录健康风险, WADA 禁用清单用于竞技语境), 体型焦虑与进食障碍风险 (男性私教肌肉变形症, 正食症倾向, NEDA 负责任语言指南), 健身房掠夺性销售 (高压推销、误导性对比照、长约锁定), 执业边界违规 (私教诊断伤病或超范围开饮食处方), 线上教练认证造假 (周末速成、未经认可的认证)。不含: 物理治疗 / 康复治疗 (持照医疗职业), 不含: 团课教练 (Les Mills/Zumba/CrossFit 分馆教练 — 相邻但不同), 不含: 精英竞技运动教练 (团队项目周期化, 不同职业路径), 不含: 营养作为主业 (临床营养学需单独资质)。.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="健身私教 — 为客户设计、指导和推进个性化训练方案的专业工艺, 有别于团课教练、物理治疗师或运动队教练: (a) 训练方案设计与周期化 (线性 / 波动 / 板块周期化 Bompa & Haff; NSCA《力量训练与体能训练精要》行业圣经; Schoenfeld 肌肥大机制; Helms/Valdez/Morgan 肌肉与力量金字塔; 共轭训练法 Simmons/Westside; Starting Strength 线性渐进 Rippetoe; Renaissance Periodization 训练量地标 Israetel); (b) 动作评估与筛查 (FMS 功能性动作筛查 Gray Cook; NASM CEx 纠正性训练连续体 抑制-拉伸-激活-整合; 关节逐级方法 Cook/Boyle; 姿势与代偿模式识别; PAR-Q+ 与 ACSM 运动前筛查指南); (c) 教学与指令 (外部 vs 内部注意焦点 Wulf; 差异化学习 Schöllhorn; 约束导向方法 Davids/Renshaw; RIR/RPE 自动调节 Zourdos/Helms; 动机访谈在健身中的应用 Rollnick/Miller); (d) 营养指导的执业边界 (宏量营养素周期化; Precision Nutrition / ISSN 立场声明的循证建议; 边界: 私教提供一般性指导, 医学营养治疗需 RD/RDN 资质; 能量可用性与 RED-S Mountjoy IOC 共识); (e) 商业与客户管理 (客户留存与方案依从; 咨询与销售伦理; 线上教练平台与规模化 Goodman PTDC; 方案交付工具 TrueCoach/Trainerize/TrainHeroic; 课时定价模型; 独立教练 vs 健身房雇员); (f) 专项方向 (运动表现 CSCS; 纠正性训练 CES; 老年健身 SFN; 产前产后; 青少年 YSCA; 适应性 / 无障碍健身; 健美 / 形体; 力量举; 耐力运动 S&C)。诚实处理: 兄弟科学 vs 循证之争, 补剂行业利益冲突, 合成代谢激素使用现状 (诚实但不推广: 匿名调查约 30% 有经验男性健身者使用过 — 业内估, Kanayama/Pope/Hudson 记录健康风险, WADA 禁用清单用于竞技语境), 体型焦虑与进食障碍风险 (男性私教肌肉变形症, 正食症倾向, NEDA 负责任语言指南), 健身房掠夺性销售 (高压推销、误导性对比照、长约锁定), 执业边界违规 (私教诊断伤病或超范围开饮食处方), 线上教练认证造假 (周末速成、未经认可的认证)。不含: 物理治疗 / 康复治疗 (持照医疗职业), 不含: 团课教练 (Les Mills/Zumba/CrossFit 分馆教练 — 相邻但不同), 不含: 精英竞技运动教练 (团队项目周期化, 不同职业路径), 不含: 营养作为主业 (临床营养学需单独资质)。"
TOPIC="训练"

usage() {
  cat <<EOF
topic-2.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 3 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-2.sh             # interactive
  ./topic-2.sh --dry-run   # walk through but no file
  ./topic-2.sh --json      # JSON to stdout
  ./topic-2.sh --explain   # show backing playbook rules + mental models
  ./topic-2.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 训练 主题下的 playbook 规则组合成交互树。

基于 3 条规则:
  • 如果 新客户从未做过健康筛查 → 则 : 则在第一次训练前必须完成 PAR-Q+ 问卷 + ACSM 风险分层。高风险客户需要医生书面 clearance。案
  • 如果 客户训练 4-8 周未安排过减量周 → 则 : 则强制插入 1 周 deload(训练量降约 40-60%, 约, 业内估 source: T04-S024;强度维
  • 如果 客户的目标涉及体成分变化(增肌/减脂) → 则 : 则必须同时管理训练和营养两端——只管训练不管营养,或只管营养不管训练,都达不到最优结果。用 TDEE 估算 + 简单

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "新客户从未做过健康筛查"
  "客户训练 4-8 周未安排过减量周"
  "客户的目标涉及体成分变化(增肌/减脂)"
)
declare -a RULE_ACTIONS=(
  ": 则在第一次训练前必须完成 PAR-Q+ 问卷 + ACSM 风险分层。高风险客户需要医生书面 clearance。案例: 45 岁久坐男性第一次训练就做大重量深蹲,触发横纹肌溶解——PAR-Q+ 会把他标为中风险,要求医学评估后才能进入高强度训练。evidence: [T03-S001, T03-S014, T06-S005]"
  ": 则强制插入 1 周 deload(训练量降约 40-60%, 约, 业内估 source: T04-S024;强度维持)。不 deload 的累积疲劳是过度训练的前奏。案例: 客户连续 10 周大训练量后感觉\"总是累\"——回顾日志发现一个 deload 都没排过;插入 1 周 deload 后表现反弹超过之前最佳。evidence: [T04-S024, T03-S017, T01-S003]"
  ": 则必须同时管理训练和营养两端——只管训练不管营养,或只管营养不管训练,都达不到最优结果。用 TDEE 估算 + 简单的宏量跟踪(MFP / Cronometer)建立基线。案例: 客户想减脂但不愿意跟踪饮食→教练从\"每天拍照三餐\"这个最低门槛开始,逐步升级到简单的蛋白质目标→3 个月后才引入完整的宏量跟踪。evidence: [T04-S020, T02-S009, T03-S004]"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-2-decision"
fi
