#!/usr/bin/env bash
# topic-3.sh — 算法 决策助手 for 中国网站备案 与 互联网内容合规 (含 ICP 备案 主体+网站 / 公安备案 / ICP 经营许可证 增值电信 / 域名实名认证 / APP 备案 2024 工信部新规 / 等级保护测评 网安 / 算法推荐 + 深度合成 + 生成式 AI 备案 网信办 / 数据出境 + 个保法 + 数安法 合规联动 / 变更注销转移跨省迁移 — 不含 通用法律咨询 / 海外域名注册 / 网络营销 SEO / 翻墙 VPN).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="中国网站备案 与 互联网内容合规 (含 ICP 备案 主体+网站 / 公安备案 / ICP 经营许可证 增值电信 / 域名实名认证 / APP 备案 2024 工信部新规 / 等级保护测评 网安 / 算法推荐 + 深度合成 + 生成式 AI 备案 网信办 / 数据出境 + 个保法 + 数安法 合规联动 / 变更注销转移跨省迁移 — 不含 通用法律咨询 / 海外域名注册 / 网络营销 SEO / 翻墙 VPN)"
TOPIC="算法"

usage() {
  cat <<EOF
topic-3.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 1 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-3.sh             # interactive
  ./topic-3.sh --dry-run   # walk through but no file
  ./topic-3.sh --json      # JSON to stdout
  ./topic-3.sh --explain   # show backing playbook rules + mental models
  ./topic-3.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 算法 主题下的 playbook 规则组合成交互树。

基于 1 条规则:
  • 如果 服务 含 算法推荐 / 个性化推送 / 内容排序 → 则 : 则 算法推荐备案 (网信办 国家算法备案系统) 必备, 同时 用户 反算法权 + 关闭 算法推荐 入口 + 标识 算

相关心智模型:
  • 三横三纵立体备案框架: 任何一个跑在中国大陆境内的 网站 / APP / 小程序 / SaaS 都同时落在 三横 (ICP 备案 + 公安备案 + 等级保护测评) × 三纵 (主体 + 网站 + 经营性升级) 的九宫格里, 
  • 接入商责任体系 (中国独有制度): 中国法定 ICP 备案的执行单位是 接入服务商 (云厂商 / IDC), 不是 申请人自己 — 站长不能直接向工信部提交, 必须 通过 阿里云 / 腾讯云 / 华为云 等接入商 完成 信息核验 + 提

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "服务 含 算法推荐 / 个性化推送 / 内容排序"
)
declare -a RULE_ACTIONS=(
  ": 则 算法推荐备案 (网信办 国家算法备案系统) 必备, 同时 用户 反算法权 + 关闭 算法推荐 入口 + 标识 算法决策 三项 强制"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-3-decision"
fi
