#!/usr/bin/env bash
# topic-1.sh — 备案 决策助手 for 中国网站备案 与 互联网内容合规 (含 ICP 备案 主体+网站 / 公安备案 / ICP 经营许可证 增值电信 / 域名实名认证 / APP 备案 2024 工信部新规 / 等级保护测评 网安 / 算法推荐 + 深度合成 + 生成式 AI 备案 网信办 / 数据出境 + 个保法 + 数安法 合规联动 / 变更注销转移跨省迁移 — 不含 通用法律咨询 / 海外域名注册 / 网络营销 SEO / 翻墙 VPN).
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="中国网站备案 与 互联网内容合规 (含 ICP 备案 主体+网站 / 公安备案 / ICP 经营许可证 增值电信 / 域名实名认证 / APP 备案 2024 工信部新规 / 等级保护测评 网安 / 算法推荐 + 深度合成 + 生成式 AI 备案 网信办 / 数据出境 + 个保法 + 数安法 合规联动 / 变更注销转移跨省迁移 — 不含 通用法律咨询 / 海外域名注册 / 网络营销 SEO / 翻墙 VPN)"
TOPIC="备案"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 4 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 备案 主题下的 playbook 规则组合成交互树。

基于 4 条规则:
  • 如果 ICP 备案下来 → 则 : 则 30 日内 必须 补办 公安备案 (www.beian.gov.cn, 不可拖延; 拖延 直接 公安部 通报 +
  • 如果 服务 含 深度合成 (AIGC 文字 / 图像 / 视频 / 语音 / 数字人) → 则 : 则 深度合成备案 + 内容显示 / 隐式 标识 双轨 必备, 同时 用户 知情同意 + 反深度合成 救济渠道
  • 如果 业务 主体 + 法定代表人 + 网站负责人 + 域名所有人 + 接入信息 任一变化 → 则 : 则 必须 通过 接入商 → 通管局 申请 变更备案, 不能 沿用 旧备案号; 跨省迁移 实际上是 注销 + 新设, 
  • 如果 备案 被驳回 / 注销 / 关停 → 则 : 则 三层救济: (a) 接入商沟通 + 整改 + 重新提交 (90% (业内估) 案件最实际路径); (b) 各省通

相关心智模型:
  • 三横三纵立体备案框架: 任何一个跑在中国大陆境内的 网站 / APP / 小程序 / SaaS 都同时落在 三横 (ICP 备案 + 公安备案 + 等级保护测评) × 三纵 (主体 + 网站 + 经营性升级) 的九宫格里, 
  • 接入商责任体系 (中国独有制度): 中国法定 ICP 备案的执行单位是 接入服务商 (云厂商 / IDC), 不是 申请人自己 — 站长不能直接向工信部提交, 必须 通过 阿里云 / 腾讯云 / 华为云 等接入商 完成 信息核验 + 提

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "ICP 备案下来"
  "服务 含 深度合成 (AIGC 文字 / 图像 / 视频 / 语音 / 数字人)"
  "业务 主体 + 法定代表人 + 网站负责人 + 域名所有人 + 接入信息 任一变化"
  "备案 被驳回 / 注销 / 关停"
)
declare -a RULE_ACTIONS=(
  ": 则 30 日内 必须 补办 公安备案 (www.beian.gov.cn, 不可拖延; 拖延 直接 公安部 通报 + 严重 关停)"
  ": 则 深度合成备案 + 内容显示 / 隐式 标识 双轨 必备, 同时 用户 知情同意 + 反深度合成 救济渠道"
  ": 则 必须 通过 接入商 → 通管局 申请 变更备案, 不能 沿用 旧备案号; 跨省迁移 实际上是 注销 + 新设, 不是 简单变更"
  ": 则 三层救济: (a) 接入商沟通 + 整改 + 重新提交 (90% (业内估) 案件最实际路径); (b) 各省通管局 行政复议 (60 日内, 形式审查为主); (c) 行政诉讼 (难度极高, 救济率低, 重点在 不能 立即 复活 业务); 关键 在 预防 + 不要 走到 第三层"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
