#!/usr/bin/env bash
# topic-1.sh — �� 决策助手 for 留学咨询规划.
# Auto-generated by cli_writer.py. Source: synthesis.md Section 2 (Playbook).
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="留学咨询规划"
TOPIC="��"

usage() {
  cat <<EOF
topic-1.sh — ${TOPIC} 决策助手 for ${INDUSTRY}

基于 6 条 playbook 规则的交互式决策评估。
你描述情景, 工具帮你判断哪条规则适用, 并给推荐。

USAGE:
  ./topic-1.sh             # interactive
  ./topic-1.sh --dry-run   # walk through but no file
  ./topic-1.sh --json      # JSON to stdout
  ./topic-1.sh --explain   # show backing playbook rules + mental models
  ./topic-1.sh --help      # this message
EOF
}

explain() {
  cat <<'EOT'
这个决策助手把 �� 主题下的 playbook 规则组合成交互树。

基于 6 条规则:
  • 如果 学生/家长初次咨询就问「能保证进什么学校」 → 则 : 则明确告知没有任何合法途径可以「���证录取」。任何声称「保录取」的机构要么在欺诈要么在利用信息不对称。案例: Op
  • 如果 学生标化成绩低于目标校 25th percentile 且��法提升 → 则 : 则评估 test-optional ���略的利弊——不提交低分可能比提交低分更好，但部分顶尖�� (MIT/Dar
  • 如果 发现学生��活动经历有「造假/夸大」嫌疑 → 则 : 则立即停止并严肃警告法律和道德后果——一旦被发现，后果包括 offer 撤销、已授学位取消、永久记录。案例: 202
  • 如果 服务 commission-based (院校返佣) 模式下被要求推荐特定学校 → 则 : 则向学生/家长明确披露返佣��系——隐瞒利益冲突是行业最大信任危机来源。案例: NACAC SPGP 明确要求 co
  • 如果 签证面签模拟���发现学生回答与 DS-160 信息矛盾 → 则 : 则立即暂停模拟、核实信息一致性——面��官最敏感的红旗是「材料和口述不一致」，一旦触发���签极难翻盘。案例: F-
  • 如果 AI 工具检测到学生文书有高比例 AI 生成痕迹 → 则 : 则要求学生完全重写而非修改——2025 年后约 68% 院校已引入 AI 检测工具 (业内估)，「修改 AI 文书使

来源: synthesis.md Section 2.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a RULE_CONDITIONS=(
  "学生/家长初次咨询就问「能保证进什么学校」"
  "学生标化成绩低于目标校 25th percentile 且��法提升"
  "发现学生��活动经历有「造假/夸大」嫌疑"
  "服务 commission-based (院校返佣) 模式下被要求推荐特定学校"
  "签证面签模拟���发现学生回答与 DS-160 信息矛盾"
  "AI 工具检测到学生文书有高比例 AI 生成痕迹"
)
declare -a RULE_ACTIONS=(
  ": 则明确告知没有任何合法途径可以「���证录取」。任何声称「保录取」的机构要么在欺诈要么在利用信息不对称。案例: Operation Varsity Blues 的 William Rick Singer 用\$2500万贿赂网络「保证」录取，所有参与者均获刑 (evidence: [T01-S011, T01-S027])"
  ": 则评估 test-optional ���略的利弊——不提交低分可能比提交低分更好，但部分顶尖�� (MIT/Dartmouth 2025 后恢复要求) 不接受 test-optional。案例: 2024 后约 50% Top 50 校恢复标化要求，纯 test-optional 策略的红利窗口在收窄 (evidence: [T03-S002, T04-S001])"
  ": 则立即停止并严肃警告法律和道德后果——一旦被发现，后果包括 offer 撤销、已授学位取消、永久记录。案例: 2024 年加州 Yi Chen & Yixin Li 案，虚假签证申请代写被 FBI 追诉 (evidence: [T01-S011, T01-S018])"
  ": 则向学生/家长明确披露返佣��系——隐瞒利益冲突是行业最大信任危机来源。案例: NACAC SPGP 明确要求 counselor 披露与院校的财务关系 (evidence: [T04-S001, T03-S003])"
  ": 则立即暂停模拟、核实信息一致性——面��官最敏感的红旗是「材料和口述不一致」，一旦触发���签极难翻盘。案例: F-1 面签 221g administrative processing 由信息矛盾触发率约 30% (业内估, evidence: [T03-S008, T03-S017])"
  ": 则要求学生完全重写而非修改——2025 年后约 68% 院校已引入 AI 检测工具 (业内估)，「修改 AI 文书使其通过检测」��「从真实经历重新写」风险更���。案例: GPTZero/Turnitin AI Detection 误判率约 15-20% (业内估)，但真 AI 文书被抓概率在上升 (evidence: [T03-S006, T03-S010])"
)
declare -a APPLIED_RULES=()

ms_section "${INDUSTRY} · ${TOPIC} 决策评估"
ms_info "本工具基于 ${#RULE_CONDITIONS[@]} 条 playbook 规则评估你的情景。"
echo

ms_prompt "请描述当前情景 (空行结束):"
echo
SITUATION="$(ms_read_multiline)"

for i in "${!RULE_CONDITIONS[@]}"; do
  ms_section "Rule $((i+1))/${#RULE_CONDITIONS[@]}"
  echo "适用情景: ${RULE_CONDITIONS[$i]}"
  echo "推荐做法: ${RULE_ACTIONS[$i]}"
  if ms_confirm "这条规则 fit 你当前情景吗?"; then
    APPLIED_RULES+=("$((i+1))")
    ms_ok "适用 rule $((i+1))"
  fi
done

ms_buffer_append "# ${INDUSTRY} — ${TOPIC} 决策报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## 情景"
ms_buffer_append ""
ms_buffer_append "$SITUATION"
ms_buffer_append ""
ms_buffer_append "## 适用规则"
ms_buffer_append ""
if [[ ${#APPLIED_RULES[@]} -eq 0 ]]; then
  ms_buffer_append "(无适用 playbook 规则 — 此情景在已知 OS 之外, 建议回到 SKILL.md 心智模型层重新分析)"
else
  for ridx in "${APPLIED_RULES[@]}"; do
    i=$((ridx-1))
    ms_buffer_append "- **情景**: ${RULE_CONDITIONS[$i]} → **做法**: ${RULE_ACTIONS[$i]}"
  done
fi
ms_buffer_append ""

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "topic" "${TOPIC}" \
    "situation" "${SITUATION}" \
    "applied_rules_count" "${#APPLIED_RULES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "topic-1-decision"
fi
