#!/usr/bin/env bash
# board-investor-relations.sh — 董事会与投资人沟通 (Board & Investor Relations) SOP walkthrough for CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。"
WORKFLOW="董事会与投资人沟通 (Board & Investor Relations)"

usage() {
  cat <<EOF
board-investor-relations.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./board-investor-relations.sh             # interactive
  ./board-investor-relations.sh --dry-run
  ./board-investor-relations.sh --json
  ./board-investor-relations.sh --explain
  ./board-investor-relations.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "董事会与投资人沟通 (Board & Investor Relations)" 工作流。

一句话: CEO 对董事会负责（fiduciary duty），对投资人负责（公开市场 / 私募 LP）—— 季度 board pack / 6-pager（Amazon 范式取代 ppt） / 致股东信 / 季度 earnings call / 半年度 1:1 sweep / 年度 AGM 共同构成「治理 OS」。董事会满意 = CEO 任期延续；董事会失信 = 90 天内被解雇（Pichai 多次警告 / Mulally Boeing 离任 / Disney Iger 复职 / OpenAI Altman 五日危机均为样本）。 (evidence: [T03-S004, T03-S060, T03-S062, T03-S063, T03-S064, T03-S065, T03-S081])

入门 SOP 共 1 步, 失败模式自检 21 项。

相关心智模型:
  • 资本配置 = CEO 最高杠杆工作 (Capital Allocation as the #1 Job): 「CEO 一辈子要做的几十个决策中, 资本配置 (5 levers: 内部再投 / 并购 / 派息 / 回购 / 还债) 的复利结果决定企业 20 年后的市值排序; 不算 hurdle rate / 
  • 战略转折点 + 主动 paranoia (Strategic Inflection Point + Paranoia as Discipline): 「10x 力 (技术 / 竞争 / 监管 / 用户行为) 改变行业基本面时, CEO 必须最先识别 + 主动毁掉一部分老业务穿越 SIP (Intel 1985 退 DRAM / 任正非 1998 华

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "季度 board meeting 前 2 周准备 6-pager（CEO 主撰，CFO + 各 SLT supplement，主题：战略进展 / 财务 / 关键风险 / 关键决策需 board input 项）；2. board meeting 前 24-48 小时发 board pack（含 6-pager + financial deck + risk register + management discussion）；3. board meeting 开场 silent reading 30 min（Amazon 范式 — 不读 ppt，直接读 6-pager）；4. 主题讨论（CEO 引导，让 board 问尖锐问题，关键决策项 board vote）；5. executive session（CEO 与 SLT 离场，独立董事单独议 — CEO 评估 / 治理 / 接班）；6. 记录决议 + action items + 90 天 follow-up；7. 半年度致股东信（致全员或公开版 — Buffett / Bezos / Patrick Collison 范式）；8. 季度 earnings call（公开公司 — IR 团队 + CFO + CEO 三角，Q&A 30+ min，要 forecast/actual 一致性）；9. 半年度 board 1:1 sweep（CEO 与每位董事单独 1 小时，听不满 + 校准 + 治理信号）。"
)
declare -a FAILURE_MODES=(
  "\"Board surprise\" (Welch / Horowitz / Sequoia 反复警告): CEO 在 board meeting 抛出 bad news 让 board 措手不及 → 信任崩 + CEO 任期倒计时。"
  "触发原因: CEO 想给好印象 / 怕预先讨论失控。"
  "怎么避免: 半年度 1:1 sweep + ad-hoc 紧急时 24h 内 alert，meeting 上只确认 — Horowitz 反复强调「board 不应该从媒体读到自己公司的新闻」。"
  "\"PPT theater\": 用 100+ slide deck 走流程，无真讨论 → board 沦为橡皮章 → 危机时 board 失声 (Boeing / WeWork / Theranos 共同模式 — 各自 board 都未真审过关键决策)。"
  "触发原因: CEO 想主导 narrative / 怕 silent reading 暴露不足。"
  "怎么避免: 6-pager + silent reading 范式 (Bezos / Bryar-Carr) — pre-read + meeting 直接讨论决策项 + executive session 让独立董事单独议。"
  "\"Letter as marketing\": 致股东信变 PR / IR talking point → 投资人折现可信度 → 估值 multiple 永久压缩 (Patrick Collison 警告: \"letter 的目的不是让人买股票，是让 10 年后的自己也能引用\")。"
  "触发原因: IR 团队主笔 / 法务删除一切风险表述。"
  "怎么避免: Buffett 范式 — 强制写 mistakes + 不讲 fluff + CEO 亲笔（Buffett 60 年自己写，从不外包）。"
  "\"Ignore activist signal\" (Trian P&G / Elliott Twitter / Starboard Salesforce 多个案例): 维权投资人露面后 CEO 拒绝 engage → 代理战丢失 / 被迫接受 board seat。"
  "触发原因: CEO 个人情绪 / 觉得维权方「错误的人」。"
  "怎么避免: 13D 出现 30 天内主动 engage + 议程预案 (Wachtell Lipton 2024 playbook) + 准备 settlement framework 防代理战升级。"
  "\"Chair-CEO confusion\": CEO 兼 chair 时（美国 ~50%）无独立挑战者 → 治理失效（Boeing / Wells Fargo / WeWork / Theranos 共同模式）。"
  "触发原因: 创始人传统 + 董事会不强势 + 投资人未要求拆分。"
  "怎么避免: 独立 lead director 实权 + executive session 制度化 (每次 board meeting 必有) + 必要时拆 chair-CEO (越来越多投资人要求)。"
  "\"Earnings whisper miss\": 给 guidance 但季度 miss → 股价 1 日 -10%，CEO 信誉 12+ 月修复 (academic 研究: missed guidance 后 CEO 平均 12-18 月被换概率上升 ~3x)。"
  "触发原因: 给 aggressive guidance 取悦 sell-side + 缺乏季度滚动调整勇气。"
  "怎么避免: under-promise over-deliver + conservative guidance + 季度滚动调整时透明 (Mulally 范式: 业务 condition 变 → 提前 pre-announce, 不等季度末)。"
  "\"Investor day theater\": 一年 1 次 investor day 给 5 年 plan，但 6 月就漂移 → 投资人记仇。"
  "触发原因: 想 push 估值，给 aggressive 5 年 plan。"
  "怎么避免: 5 年 plan 给 range + 每季度滚动校准 + 公开校准理由 (Patrick Collison Stripe 范式)。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "board-investor-relations-walkthrough"
fi
