#!/usr/bin/env bash
# capital-allocation.sh — 资本配置决策 (Capital Allocation) SOP walkthrough for CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。"
WORKFLOW="资本配置决策 (Capital Allocation)"

usage() {
  cat <<EOF
capital-allocation.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./capital-allocation.sh             # interactive
  ./capital-allocation.sh --dry-run
  ./capital-allocation.sh --json
  ./capital-allocation.sh --explain
  ./capital-allocation.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "资本配置决策 (Capital Allocation)" 工作流。

一句话: CEO 单一最高杠杆的工作（Thorndike《The Outsiders》论 8 位非常规 CEO 的核心论点）—— 把每一元自由现金流分配到 5 个杠杆（organic reinvestment / acquisition / dividend / share buyback / debt paydown），用 hurdle rate（资金机会成本）作为门槛纪律，公开复盘 ROI。Buffett 60 年致股东信 / Mark Leonard 11 年 letters / Bezos AWS-Kindle-Prime 三大 bet 都是这套 workflow 的范本。 (evidence: [T03-S005, T03-S006, T03-S007, T03-S008, T03-S009, T03-S010])

入门 SOP 共 1 步, 失败模式自检 18 项。

相关心智模型:
  • 资本配置 = CEO 最高杠杆工作 (Capital Allocation as the #1 Job): 「CEO 一辈子要做的几十个决策中, 资本配置 (5 levers: 内部再投 / 并购 / 派息 / 回购 / 还债) 的复利结果决定企业 20 年后的市值排序; 不算 hurdle rate / 
  • 战略转折点 + 主动 paranoia (Strategic Inflection Point + Paranoia as Discipline): 「10x 力 (技术 / 竞争 / 监管 / 用户行为) 改变行业基本面时, CEO 必须最先识别 + 主动毁掉一部分老业务穿越 SIP (Intel 1985 退 DRAM / 任正非 1998 华

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "列出 5 levers 当前金额（organic capex / acquisition / dividend / buyback / debt paydown）+ 持有现金；2. 计算每条 IRR（organic = NPV of project / acq = synergy-adjusted IRR / buyback = earnings yield ÷ stock price / dividend = signaling value / debt paydown = after-tax rate），与公司 hurdle rate (Mauboussin 范式: WACC + 风险溢价) 对照；3. 写 1 页 thesis（为什么本季度选 X lever，假设 + 风险 + 12 月后如何判定对错）；4. 提交董事会审议（典型 4 季度 + 年中 ad-hoc）；5. 公告投资人（10-Q / 致股东信 / earnings call）；6. 季度复盘（实际 vs thesis）；7. 年度致股东信公开复盘（Buffett 范式: 哪些 bet 错了，承认 + 学到什么）。"
)
declare -a FAILURE_MODES=(
  "\"Welch-style EPS engineering\": 用 buyback / 削 R&D 拉短期 EPS，长期破坏复利能力 — GE 后遗症（Gelles《The Man Who Broke Capitalism》）→ 一代 CEO 离任后公司空心化。"
  "触发原因: 股票期权 + 短期 EPS 压力 + 维权投资人逼回购。"
  "怎么避免: 公开 hurdle rate + 长期 metric (10-year IRR not 1-year EPS) + 致股东信明示长期 vs 短期取舍。"
  "\"Acquisition theater\": 为「我们要长大」收购，不算 synergy IRR — 70-80% M&A 跑输 hurdle rate（HBR / McKinsey / KPMG 多项研究共识）。"
  "触发原因: 投行 deal flow 推 + CEO 觉得「不收就被收」+ 没 hurdle rate 纪律。"
  "怎么避免: 强制写 1-page thesis (synergy 量化 + base rate 同行业 ROI 对照) + 12 月 post-mortem + 拒绝大型变革 M&A，小笔多 deal 为佳 (Constellation 范式)。"
  "\"Cash hoarding without thesis\": 现金堆在资产负债表上无明确 use case → 投资人维权（Carl Icahn Apple / Trian DuPont / Elliott style 多个案例）。"
  "触发原因: CEO 谨慎 / 等大机会 / 没人 push 资本配置纪律。"
  "怎么避免: 季度公开 capital allocation thesis，说明为何持现金（等估值合理的 acq 机会 / 利率高时 4%+ T-bills 自然收益 / 危机备粮）— 不是「无策略」而是「显式策略」。"
  "\"Never explain mistakes\": 不在致股东信认错 → 投资人折现信任 → 估值 multiple 永久压缩 (academic 研究: 不认错的 CEO P/E 比认错的低 ~15% on average)。"
  "触发原因: 法务怕集体诉讼 / IR 怕股价波动 / CEO 自尊。"
  "怎么避免: Buffett 范式 — 年度信公开列出 mistakes (Buffett 1989/2014/2022 letters 都有专门 mistakes 段落)。"
  "\"Pet project bias\": CEO 偏爱某条线（创始人情怀 / 自己的 baby），不让其经受 hurdle rate 检验 → 长期消耗资本（Welch GE Capital / Branson Virgin 系列 / Musk Cybertruck 是不同程度样本）。"
  "触发原因: founder 情感投入 + SLT 不敢挑战 + 无外部 challenger。"
  "怎么避免: 让 CFO + 外部董事独立审 + 强制 base rate 对照 + 若 12 月仍不达 hurdle rate 必须砍。"
  "\"Reactive to market timing\": 牛市追 acquisition 高估值，熊市 buyback 等股价反弹 — 完全反向 (Buffett 反复警告: \"fearful when others greedy, greedy when others fearful\")。"
  "触发原因: 顺势心理 + 董事会跟着 narrative 走。"
  "怎么避免: 公司 hurdle rate 是 reference rate (不随市场波动)，capital allocation 决策只看 hurdle rate vs IRR，不看 sentiment。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "capital-allocation-walkthrough"
fi
