#!/usr/bin/env bash
# crisis-communication.sh — 危机沟通 (Crisis Communication) SOP walkthrough for CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。"
WORKFLOW="危机沟通 (Crisis Communication)"

usage() {
  cat <<EOF
crisis-communication.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./crisis-communication.sh             # interactive
  ./crisis-communication.sh --dry-run
  ./crisis-communication.sh --json
  ./crisis-communication.sh --explain
  ./crisis-communication.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "危机沟通 (Crisis Communication)" 工作流。

一句话: 公司发生重大危机（产品安全 / 数据泄露 / 高管丑闻 / 财务造假 / 监管处罚 / 重大事故 / 维权 hostile takeover / 黑天鹅 / 集体诉讼）时，CEO 必须在 30 min - 72h 内做完一系列动作 — Tylenol 范式（J&J 1982 召回 + 透明）= 黄金标准 / Boeing 737 MAX = 反面 / Wells Fargo 2016 假账户 = 反面 / Welch GE 后期 = 反面 / 任正非 2019 中外媒体圆桌 = 中国本土范式。这是 CEO 任期最高 wattage 时刻 — 做对加固任期，做错 30 天内被董事会换。 (evidence: [T03-S047, T03-S048, T03-S070, T03-S071, T03-S072, T03-S073])

入门 SOP 共 1 步, 失败模式自检 24 项。

相关心智模型:
  • 资本配置 = CEO 最高杠杆工作 (Capital Allocation as the #1 Job): 「CEO 一辈子要做的几十个决策中, 资本配置 (5 levers: 内部再投 / 并购 / 派息 / 回购 / 还债) 的复利结果决定企业 20 年后的市值排序; 不算 hurdle rate / 
  • 战略转折点 + 主动 paranoia (Strategic Inflection Point + Paranoia as Discipline): 「10x 力 (技术 / 竞争 / 监管 / 用户行为) 改变行业基本面时, CEO 必须最先识别 + 主动毁掉一部分老业务穿越 SIP (Intel 1985 退 DRAM / 任正非 1998 华

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "30 min 内召集 crisis team（CEO + GC + CFO + Comms head + 相关业务 head — 用预设 escalation list 而非临时拼），所有人到一个房间 / Zoom 不挂线；2. 1 小时内对外初步声明（3 部分必含: acknowledge — 我们知道发生了什么 / investigate — 我们在彻查 / commit — 我们会公开更新），声明先发员工再发外部（员工在媒体之前知道）；3. 24h 内首份事实更新（基于已知的事实 — 不是推测，不是辩解；what we know / what we don't know / what we're doing）；4. 72h 内 root cause hypothesis（\"根据目前调查，这个事件的可能根因是 X，我们仍在 Y / Z 维度验证\"）— Tylenol 范式: 透明 + 主动召回 + 不躲；5. 1 周内 corrective action plan（具体步骤 + 时间表 + owner + 度量 KPI）；6. 30 天内 lessons learned 公开报告（独立调查为佳 — board 委托外部 firm 而非内部）；7. 长期 governance 改造（高管问责 + 制度变更 — 比如 Wells Fargo 应该做但没做的）；8. 半年内董事会复盘 + 投资人沟通（致股东信单独段落，避免 narrative 失控）。"
)
declare -a FAILURE_MODES=(
  "\"Lawyer-mediated denial\": 法务主导让 CEO 「啥也别说」→ 媒体讲故事，公司被动 (Boeing 737 MAX / WeWork S-1 / Theranos 早期 共同模式)。"
  "触发原因: 法务怕集体诉讼 / SEC enforcement / 个人责任。"
  "怎么避免: 法务建议但 CEO 决定 — 必 acknowledge。Tylenol Burke 当时律师反对召回，Burke 拍板召回，事后回看是 J&J 长期信任货币的起点。"
  "\"Deflect blame\": 怪员工 / 怪供应商 / 怪用户 (Wells Fargo Stumpf 国会作证: \"我们 fired 5300 员工\" — 投资人翻脸 + 4 月后 Stumpf 辞职 + 政府 \$185M 罚款)。"
  "触发原因: CEO 自保 + 不理解 institutional responsibility。"
  "怎么避免: CEO 承担 institutional responsibility (任正非 范式: \"公司错了，错在我，员工问责另案\")，员工问责走流程不公开归罪。"
  "\"Slow disclosure\": 拖到 SEC / DOJ 介入才披露 (FTX 11/11 崩盘后 SBF 沉默 4 天 / Theranos 持续否认到 2018 / Boeing 737 MAX 第一起 Lion Air 事故后 5 月才接受问题真实性)。"
  "触发原因: 希望问题自己消失 / 等更多信息 / 法务建议沉默。"
  "怎么避免: 主动披露 + SEC 4 天 cyber rule 严守 + 任何重大 material event 24h 内启动 8-K 准备。"
  "\"Multiple voices\": Comms / 法务 / 业务各自对外发声 message 不一致 → 媒体抓矛盾点放大 (Boeing 初期典型 — CEO / CFO / Engineering head 三套说法)。"
  "触发原因: 没有 single spokesperson 协议 / 危机 team 没召集成功。"
  "怎么避免: single voice (CEO 或指定 spokesperson) + 所有 communication 30 min 内集中审稿 + 任何对外发言必须经 crisis team 签字。"
  "\"Vague apology\": \"We're sorry for any inconvenience\" 式空洞道歉 → 怒火更盛 (Uber / Equifax 数据泄露后均用此模板被骂)。"
  "触发原因: 法务删掉所有具体表述。"
  "怎么避免: Tylenol / Hastings Qwikster 2011 范式: 具体认错 (我们做错了什么 — 具体动作) + 承诺具体动作 (我们要做 X、Y、Z 修复) + 用第一人称 (我，不是公司)。"
  "\"No governance change\": 危机后无制度变 → 18 月再发同类危机 (Wells Fargo 2016-2024 仍未根治 Fed Consent Order 持续 6+ 年，2024 仍受限)。"
  "触发原因: 想「过这一关」就好，不愿动制度。"
  "怎么避免: lessons learned 后必有制度变 + 独立董事监督执行 + 半年董事会 audit。"
  "\"CEO ghost\": CEO 躲起来让 Comms VP 顶替 (Boeing Muilenburg 初期 — 不上电视，发文字声明) → 信任崩 → Muilenburg 1 年内辞职。"
  "触发原因: CEO 怕被记者问错 / 自我保护。"
  "怎么避免: CEO 个人露面，亲口说 + 不躲 60 Minutes / FT / 财新 / 国会作证 + 准备充分但坦诚承认不知道的事。"
  "\"Pre-crisis 准备缺位\": 没有 pre-scripted playbook + 没有 escalation list + 没有外部 PR 顾问 retainer → 30 min 召集失败 → 1h 声明 miss → 全流程崩。"
  "触发原因: 「我们不会有危机」侥幸 + 不愿花钱平时准备。"
  "怎么避免: 平时就准备 5-10 种常见危机 playbook + 季度 simulation + 外部 PR (Brunswick / Edelman / Sard Verbinnen) retainer + 法务危机 firm retainer。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "crisis-communication-walkthrough"
fi
