#!/usr/bin/env bash
# high-stakes-decisions.sh — 重大决策 (High-Stakes Decisions) SOP walkthrough for CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。"
WORKFLOW="重大决策 (High-Stakes Decisions)"

usage() {
  cat <<EOF
high-stakes-decisions.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./high-stakes-decisions.sh             # interactive
  ./high-stakes-decisions.sh --dry-run
  ./high-stakes-decisions.sh --json
  ./high-stakes-decisions.sh --explain
  ./high-stakes-decisions.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "重大决策 (High-Stakes Decisions)" 工作流。

一句话: Bezos Type 1 (irreversible 一扇单向门) vs Type 2 (reversible 双向门) 决策框架 + RAPID/DACI 角色清晰 + Klein premortem + Kahneman bias 检查 + base rate (Mauboussin) + scenario planning + Disagree and Commit 共同构成 CEO 高风险决策的工艺。CEO 每月 1-3 个 Type 1 决策（大 hire / 大 M&A / 战略 pivot / 重大资本配置），全错一个 ≈ 任期断送。 (evidence: [T03-S001, T03-S002, T03-S004, T03-S038, T03-S045, T03-S046, T03-S076])

入门 SOP 共 1 步, 失败模式自检 24 项。

相关心智模型:
  • 资本配置 = CEO 最高杠杆工作 (Capital Allocation as the #1 Job): 「CEO 一辈子要做的几十个决策中, 资本配置 (5 levers: 内部再投 / 并购 / 派息 / 回购 / 还债) 的复利结果决定企业 20 年后的市值排序; 不算 hurdle rate / 
  • 战略转折点 + 主动 paranoia (Strategic Inflection Point + Paranoia as Discipline): 「10x 力 (技术 / 竞争 / 监管 / 用户行为) 改变行业基本面时, CEO 必须最先识别 + 主动毁掉一部分老业务穿越 SIP (Intel 1985 退 DRAM / 任正非 1998 华

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "判定 Type 1 vs Type 2（\"如果错了，能逆转吗？\"— Type 2 双向门可快速试错回退，Type 1 单向门一旦决定就 lock-in）；2. Type 1 走完整 SOP — RAPID/DACI 列出谁 Recommend / Agree / Perform / Input / Decide + premortem (Klein 范式: SLT 各自匿名写「假设 12 月后失败，最可能根因」) + base rate (Mauboussin: 同类决策历史 ROI 中位数) + 等 ≥ 90% 信息 + 写 1-pager；3. Type 2 快速 70% 信息决策 (Bezos: \"如果你等到 90% 信息再决定，多数情况下，你就已经慢了\") + 试错回退 plan；4. 写 1-pager decision memo（不超过 1 页，A4，含 4 部分：背景 / 选项 / 推荐 / 12 月判定标准）；5. SLT 异议时 \"Disagree and Commit\" (Bezos 范式: 我不同意但我承诺执行，公开记录异议) — 避免「沉默的反对」12 月后翻案；6. 决策执行后 90 天 post-mortem（实际 vs thesis + 学到什么）；7. 写入 decision journal（CEO 个人 — Munger / Dalio / 段永平 都坚持，年度回顾 base rate 校准自己）。"
)
declare -a FAILURE_MODES=(
  "\"Type 1 / Type 2 confusion\": 把 Type 2 当 Type 1 过度斟酌（CEO 90% 错误模式 — 慢死，AWS S3 Bezos 反复警告: \"if you only have one decision speed, it should be Type 2 speed\")  / 把 Type 1 当 Type 2 轻率决定（剩 10% — 但致命，多是 founder mode CEO 的盲区）。"
  "触发原因: 没显式问 reversibility。"
  "怎么避免: 决策前显式问 \"reversible? cost to reverse 是多少?\" — 若 < 1% revenue 且 < 1 月 → Type 2 快决 + 试错；若不可逆或 cost > 5% revenue → Type 1 走完整 SOP。"
  "\"HiPPO bias\": Highest Paid Person's Opinion 主导，SLT 沉默 → 错决策 (academic 数据: HiPPO bias 让 SLT 错决策率 ↑ ~30%)。"
  "触发原因: CEO 先说意见 / SLT 怕得罪 / 文化未保护异见。"
  "怎么避免: Dalio believability-weighted + Disagree and Commit + Amazon 范式 (CEO 让 SLT 先说，自己最后说) + 匿名 premortem。"
  "\"Sunk cost trap\": 已投 X 资源，舍不得砍 (Theranos / Welch GE Capital / Disney+ Quibi 反复模式)。"
  "触发原因: CEO 个人投入感 + 怕承认错。"
  "怎么避免: zero-based 思考 — \"今天从零起 (with 当前信息), 我还会做这选择吗\" + 12 月 post-mortem 强制问 + 段永平范式「不为清单」预先承诺哪些情况下必砍。"
  "\"Confirmation bias\": 只听支持的数据 (Kahneman 反复警告，executive bias 第一位)。"
  "触发原因: 大脑节能 / 已经倾向某选项。"
  "怎么避免: premortem + 外部 devil's advocate + base rate 数据 + AI thought-partner 故意要 counter-thesis (Reid Hoffman Impromptu 范式)。"
  "\"No post-mortem\": 决策后无复盘 → 系统性无学习 → 同类错重复犯 (Welch / Welch-era GE 经典)。"
  "触发原因: 决策已过 / 找新事忙。"
  "怎么避免: 90 天 post-mortem 强制 (calendar 一开始就锁) + decision journal 长期归档 + 年度 self-review 自己历史决策 base rate。"
  "\"Silent disagreement\": SLT 不在 meeting 发声但 12 月后翻案 → 信任崩 (Pichai / Andreessen 多次提及)。"
  "触发原因: 怕得罪 / 不愿担责。"
  "怎么避免: Bezos \"Disagree and Commit\" 范式 — 异议必须 on-record + meeting 强制 round-robin 让每人发言 + 异议者也签字 commit。"
  "\"AI over-reliance\" (新兴): 用 AI 起草 Type 1 决策但不质疑 → AI hallucination 进决策链 (2024 多个 case 已记录 — 投行用 GPT 写 IPO prospectus 出错)。"
  "触发原因: AI 输出看起来 polished 但事实有漏。"
  "怎么避免: AI 仅做 stress-test / counter-thesis / 抓 base rate / 列盲点，最终判断人 + 关键事实 SLT 独立验证。"
  "\"Decision avoidance\": 拖延 Type 1 决策 (Mulally 接手 Ford 时发现 SLT 习惯「再调研一轮」)。"
  "触发原因: 怕错 + 等更多信息。"
  "怎么避免: 70% 信息 + reversibility plan + 给自己 deadline。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "high-stakes-decisions-walkthrough"
fi
