#!/usr/bin/env bash
# hire-fire-executive-team-buildin.sh — 高管班子搭建 / hire / fire (Executive Team Building) SOP walkthrough for CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。"
WORKFLOW="高管班子搭建 / hire / fire (Executive Team Building)"

usage() {
  cat <<EOF
hire-fire-executive-team-buildin.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./hire-fire-executive-team-buildin.sh             # interactive
  ./hire-fire-executive-team-buildin.sh --dry-run
  ./hire-fire-executive-team-buildin.sh --json
  ./hire-fire-executive-team-buildin.sh --explain
  ./hire-fire-executive-team-buildin.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "高管班子搭建 / hire / fire (Executive Team Building)" 工作流。

一句话: 高管班子 (Senior Leadership Team / SLT) 是 CEO「输出 = 下属输出之和」（Andy Grove HOM）的最高杠杆——选拔 / onboarding 90 天 / Lencioni 五大障碍诊断 / Bill Campbell coach 范式 / Horowitz 解雇高管手册 / Reed Hastings keeper test 共同构成一年级到资深 CEO 的核心工作量（CEO 把 30-50% 时间花在 talent 上是 Welch / Mulally / Nadella 共识）。 (evidence: [T03-S011, T03-S014, T03-S017, T03-S041, T03-S043, T03-S061, T03-S062])

入门 SOP 共 1 步, 失败模式自检 18 项。

相关心智模型:
  • 资本配置 = CEO 最高杠杆工作 (Capital Allocation as the #1 Job): 「CEO 一辈子要做的几十个决策中, 资本配置 (5 levers: 内部再投 / 并购 / 派息 / 回购 / 还债) 的复利结果决定企业 20 年后的市值排序; 不算 hurdle rate / 
  • 战略转折点 + 主动 paranoia (Strategic Inflection Point + Paranoia as Discipline): 「10x 力 (技术 / 竞争 / 监管 / 用户行为) 改变行业基本面时, CEO 必须最先识别 + 主动毁掉一部分老业务穿越 SIP (Intel 1985 退 DRAM / 任正非 1998 华

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "写 JD + scorecard（角色 outcome 5-7 条 + competency 5-7 条，Smart Topgrading 范式 — outcome 不是「manage X team」而是「在 Q4 前把 churn 从 X% 降到 Y%」）；2. 启动猎头（Korn Ferry / Spencer Stuart / Heidrick 三大）+ 内部推荐 + CEO 自有网络三路并行，目标 shortlist 5-8 人；3. 多轮面试（CEO + SLT 同事 + skip-level + 案例 work session + 360 reference 至少 5 人含 1 个 detractor）；4. talent 密度评估（Hastings keeper test: \"如果这人明天告诉我要走，我会全力挽留还是松口气？\"）；5. offer + 90 天 onboarding（30 天 listening / 60 天 plan / 90 天 first delivery）；6. 季度评估（OKR + 文化 fit + 团队反馈）；7. 必要时果断解雇（Horowitz: 决定下了就别拖，最长 1 周内执行；公开诚实告知 SLT + 全员）。"
)
declare -a FAILURE_MODES=(
  "\"Hiring for credentials not outcomes\": 招了名校 / 大公司高管但具体战役没打过 → 18 月失败（Smart Topgrading 数据: mishire 占新高管 ~50%, 平均成本 = 年薪 15x）。"
  "触发原因: CEO 看简历 / 看 logo / 不愿做 work session 验证。"
  "怎么避免: scorecard 强写 outcome (不是 \"manage X team\" 而是 \"Q4 前把 churn 从 X% 降到 Y%\") + reference 强问「他在 X 战役做了什么具体动作」+ work session 让候选人现场做你公司真实的 1 个问题。"
  "\"Slow firing\": 已决定要 fire 但拖 3-6 月（CEO 软弱 / 找替代 / 怕动荡） → \"the cancer spreads\" (Horowitz), SLT 信任崩。"
  "触发原因: CEO 没替代 + 担心面子 / 离职费 / 业务空档。"
  "怎么避免: Horowitz 范式 — 决定下了 1 周内执行，公开诚实告知 SLT + 全员 (不污名化 — \"X 与公司方向不再 fit\"), 临时由 CEO 直接 cover 该岗 8-12 周再 hire。"
  "\"No onboarding plan\": 新高管「自己摸索」→ 3 月发现方向偏，3 月 fix，6 月才上轨道，年化失败率高。"
  "触发原因: CEO 觉得「资深高管不需要 onboarding」。"
  "怎么避免: 30/60/90 plan 第一天就给 + CEO 第 1 月每周 1:1 + skip-level 听新高管被团队评价 + 90 天 deliverable 强制。"
  "\"Tolerating brilliant jerks\": 业绩好但文化烂的高管，CEO 不敢动 → 中层 A-player 流失（Hastings 反复警告，2020 起 Netflix 明确 \"No brilliant jerks\"; Uber Kalanick 时期是反面教科书）。"
  "触发原因: 业绩 KPI 单维评估 + CEO 怕失业绩。"
  "怎么避免: 文化与业绩同等权重在 review + 一票否决 — culture red 即触发 fire (Horowitz / Hastings 共识) + 公开 SLT 价值观考核。"
  "\"Underinvest in coaching\": 高管成长靠「在岗学」→ 18 月触天花板，SLT 同质化。"
  "触发原因: 觉得 coach 是「修补差高管」(stigma) 而非「打磨好高管」。"
  "怎么避免: Bill Campbell 范式 — 关键高管配外部 coach (Marshall Goldsmith / Kim Scott 等)，coach 不是 mentor，问问题逼对方说出答案。Trillion Dollar Coach 详述。"
  "\"Hire CFO/COO as kingmaker without governance\": 创始人 hire 强 CFO/COO 让对方实际 run 公司但治理上 CEO 仍 own → 双头管理 + 责任不清。"
  "触发原因: founder 想退后台但又不放弃 title。"
  "怎么避免: 角色清晰 + board 公开 + 必要时 founder→executive chair (workflow 8 范式)。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "hire-fire-executive-team-buildin-walkthrough"
fi
