#!/usr/bin/env bash
# stage-transition-0-1-1-100-matur.sh — 跨阶段切换 (Stage Transition: 0→1 / 1→100 / mature / turnaround) SOP walkthrough for CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。"
WORKFLOW="跨阶段切换 (Stage Transition: 0→1 / 1→100 / mature / turnaround)"

usage() {
  cat <<EOF
stage-transition-0-1-1-100-matur.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./stage-transition-0-1-1-100-matur.sh             # interactive
  ./stage-transition-0-1-1-100-matur.sh --dry-run
  ./stage-transition-0-1-1-100-matur.sh --json
  ./stage-transition-0-1-1-100-matur.sh --explain
  ./stage-transition-0-1-1-100-matur.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "跨阶段切换 (Stage Transition: 0→1 / 1→100 / mature / turnaround)" 工作流。

一句话: 公司 + CEO 跨阶段 — 0→1 founder mode (Paul Graham / Brian Chesky 范式) → 1→100 scaling (Reid Hoffman Blitzscaling) → mature stewardship (Buffett / Cook / Pichai 范式) → turnaround (Lou Gerstner IBM / Alan Mulally Ford / 稻盛和夫 JAL 范式)。每个 stage 的「OS」(组织架构 + meeting cadence + capital allocation + culture) 完全不同 — 跨 stage 不切换 OS = 公司死 / CEO 被换。Paul Graham 2024 "Founder Mode" 重新点燃这场辩论。 (evidence: [T03-S023, T03-S024, T03-S025, T03-S026, T03-S027, T03-S028, T03-S060, T03-S078])

入门 SOP 共 1 步, 失败模式自检 24 项。

相关心智模型:
  • 资本配置 = CEO 最高杠杆工作 (Capital Allocation as the #1 Job): 「CEO 一辈子要做的几十个决策中, 资本配置 (5 levers: 内部再投 / 并购 / 派息 / 回购 / 还债) 的复利结果决定企业 20 年后的市值排序; 不算 hurdle rate / 
  • 战略转折点 + 主动 paranoia (Strategic Inflection Point + Paranoia as Discipline): 「10x 力 (技术 / 竞争 / 监管 / 用户行为) 改变行业基本面时, CEO 必须最先识别 + 主动毁掉一部分老业务穿越 SIP (Intel 1985 退 DRAM / 任正非 1998 华

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "诊断当前 stage（员工头数 + 收入阶段 + 市场地位 + 现金流 + 增速 — 比如 100 人内为 0→1，100-2000 为 scaling，2000-20000 为 mature, ≥ 20000 + 多业务为 conglomerate / 平台）；2. 识别需要切换信号（员工抱怨「失控 / 流程缺」/「流程太多 / 创始人疏远」 + 关键决策延迟 + SLT 失效 + 关键 hire 失败 + 客户流失 + 战略转折点信号）；3. 评估 founder 能否切换 OS（\"我能从 5 人扁平 founder mode 切到 SLT cascade / OKR / WBR / 6-pager 节奏吗？我愿意吗？\" — 段永平 / 张一鸣 范式: 不愿就早交班）；4. 必要时 hire COO 过渡（COO 跑 OS, founder 跑产品 / 战略 / culture — Tim Cook→COO→CEO 范式）或 founder→executive chair (Bezos 2021 / Brin-Page-Pichai 范式 / Hastings 2020 给 Sarandos)；5. 重写 OS（组织架构 — functional vs business unit vs matrix；meeting cadence — WBR/OP/QBR；capital allocation — 5 levers 权重；culture — 文化 OS 升级）；6. 90 天 transition plan（每周 milestone + SLT 同步 + board 同步 + 全员沟通）；7. 12-24 月稳态评估（OKR 完成度 + culture survey + 业绩 + 关键 hire 留存 + 决策速度）。"
)
declare -a FAILURE_MODES=(
  "\"Founder over-stays\": 5000 人公司还用 5 人扁平 founder mode → 关键决策延迟 + SLT 失效 (Kalanick Uber 2015-2017 经典 / Neumann WeWork 2017-2019 / Theranos Holmes 全程)。"
  "触发原因: founder 自我认同 + 觉得「manager mode 是平庸」+ 没诚实自评。"
  "怎么避免: 主动 stage audit + 诚实自评 + 360 + 外部 coach + 必要时 founder→chair (Bezos / Hastings 范式)。"
  "\"Hire COO 但 founder 仍微管理\": COO 沦为执行木偶，OS 不真切换 (常见硅谷模式 — 多数 founder hire COO 后 12-18 月 COO 离职)。"
  "触发原因: founder 想「保留控制 + 不用承担 OS 苦活」两头要。"
  "怎么避免: 角色清晰 (RAPID 矩阵) + COO 真 own ops + founder 退到产品 / 战略 / culture / IR + board 公开背书 COO 决策权。"
  "\"Wholesale culture replacement\": turnaround CEO (Gerstner / Mulally) 错以为要彻底换文化 — Gerstner 反而保留 IBM \"respect for individual\"，只换 process (官僚 / 内斗) (Gerstner 自述: \"如果我换了 IBM 的灵魂, 我会输\")。"
  "触发原因: 新 CEO 觉得「老文化是问题」一刀切。"
  "怎么避免: 区分 toxic process vs 良性 culture (头 6 周纯听 — Gerstner / Nadella 范式)，只动前者，保留后者 + 显式背书。"
  "\"Premature founder exit\": 创始人退太早 (Disney Eisner→Iger→Chapek 失败→Iger 2022 复职; OpenAI 2023-11 — board 误判 founder 退场后果)。"
  "触发原因: board 觉得「专业 CEO 一定更好」/ founder 自己想 retire。"
  "怎么避免: founder 跑不动了 ≠ founder 该走 — 评估「founder unique value」(产品判断 / 文化 / 创业精神 / 客户关系) 仍在没在；若仍在 → founder mode hybrid (Chesky 范式) 而非全退。"
  "\"OS lag\": 公司从 0→1 进 1→100 但仍用 0→1 工具 (Slack / Notion / 无 OKR / 无 WBR / 无 6-pager) → 增长后 18 月内崩 (Quibi / 多个 SaaS startup 失败模式)。"
  "触发原因: founder 抗拒「企业化」「官僚化」。"
  "怎么避免: 跨头数坎 (100 / 500 / 2000) 主动重写 OS — workflow 1 / 4 / 5 全套上线 + COO/CFO/CHRO 三人到位。"
  "\"Turnaround heroics without governance\": Lou Gerstner / Mulally 成功是因为有强 board 授权 — 弱 board / 强 founder 仍掌权时 turnaround CEO 没空间 (多个失败 turnaround CEO 都死于 founder/chair 不放权)。"
  "触发原因: board 不愿真授权 / 创始人 chair 干预日常。"
  "怎么避免: 接 turnaround 必先确认 board 授权范围 + 90 天 stake + 必要时拆 chair-CEO + 拒绝接 founder 仍 chair 且活跃干预的 turnaround。"
  "\"Cargo cult founder mode\": 把 Paul Graham 2024 essay 误解为「所有 founder 都该 founder mode 永远」(Stratechery 反复警告) → 跨 stage 不切换 → 重复 Kalanick / Neumann 错。"
  "触发原因: founder mode essay 引起共鸣 + 忽略 Chesky 实际是 hybrid mode (不是全 founder mode)。"
  "怎么避免: 阅读 Chesky 详述 + 区分「founder unique value 仍 in」(则 hybrid) vs 「founder 真 hit 上限」(则 founder→chair)。"
  "\"无接班准备\": founder 健康 / 偶发 / 突发离职无 ready successor (OpenAI 2023-11 board 把 Altman 解雇时无清晰接班人 → 4 天混乱)。"
  "触发原因: founder 不愿承认有一天会走 + board 怕得罪 founder。"
  "怎么避免: 任正非 范式 — 轮值 CEO 制度 + 持续培养 3-5 个潜在接班人 + 每年 board succession review。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "stage-transition-0-1-1-100-matur-walkthrough"
fi
