#!/usr/bin/env bash
# wbr-weekly-business-review-opera.sh — WBR / 节奏运营 (Weekly Business Review & Operating Rhythm) SOP walkthrough for CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。.
# Auto-generated by cli_writer.py. Source: research/03-workflows.md.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../lib/common.sh"

INDUSTRY="CEO (Chief Executive Officer) — 一家公司「最高操作员」的工艺, 与泛泛「领导力 / 管理学」不同: (a) 设定战略与凝结愿景 (Drucker 的「企业的经营理论」+ Porter 论定位 + Hamilton Helmer 的「七力」+ Andy Grove 的「战略转折点」+ Roger Martin 《Playing to Win》); (b) 资本配置是 CEO 单一最高杠杆的工作 (Buffett/Munger Berkshire 致股东信 + William Thorndike 《The Outsiders 商界局外人》论 8 位非常规 CEO + Michael Mauboussin 论 hurdle rate + Bezos 年度致股东信「invariants vs bets」+ Mark Leonard Constellation Software); (c) 组建与领导高管班子 (Patrick Lencioni 《团队的五大障碍》+ Ben Horowitz 《艰难的事》+ Reed Hastings 《No Rules Rules》人才密度 + Andy Grove HOP《高产出管理》+ Lou Gerstner IBM 转型 + Marshall Goldsmith); (d) 董事会与投资人关系 (Larcker & Tayan 《公司治理重要》+ Bill George 《True North》+ 正式 CEO-董事长 / CEO-独立董事 protocol + 维权投资人 playbook + 资本市场沟通); (e) 企业文化与价值观作为操作系统 (Netflix 文化手册 + Amazon Leadership Principles + Bridgewater 《Principles》Ray Dalio + Schein 论组织文化 + 任正非 灰度 + 张瑞敏 人单合一 + 稻盛和夫 阿米巴); (f) 高不确定下的高风险决策 (Bezos Type 1/Type 2 决策 + premortem Klein + Kahneman 论 executive bias + RAPID/DACI + base rates + 情景规划 + 反思 premortem); (g) 对内对外沟通 (创始人 / CEO 致股东信作为机构构建工具: Bezos / Buffett / Reed Hastings 备忘录 / 任正非 内部讲话 + Town Hall + 危机沟通 Tylenol/Boeing/Wells Fargo + 应对维权投资人); (h) 跨阶段规模化 (创业 0→1 / 扩张 1→100 / 成熟期掌舵 / 危机转型): Steve Blank + Brian Chesky founder-mode + Marc Andreessen + Pierre Lassonde + Lou Gerstner 转型; (i) 创始人 CEO vs 职业经理人 CEO 的差异 (Paul Graham 「Founder Mode」2024 + Brian Chesky + Reed Hastings (创始人→职业过渡) + BCG/McKinsey 的「manager mode」+ 两者各自代价 + 什么时候切换)。诚实处理: 幸存者偏差 (单个 CEO 的打法 ≠ 普适规律, 学术研究显示 CEO 个人方差约 ⅓, 约 70% 来自行业 / 时代 / 运气 / 资本结构), 创始人崇拜, 区分可复制工艺与不可移植个人魅力, 治理与利益相关者责任 (员工 / 股东 / 社会), 反对 CEO 神话与 Welch 退休金扭曲 / Theranos / WeWork / FTX / Uber-Kalanick 时代 / Musk 80h+ / 996 工时崇拜。覆盖 founder-CEO (Bezos/Hastings/黄仁勋/Chesky/Brin/任正非) 与职业 CEO (Nadella/Gerstner/Pichai/Mulally/Lafley)。不含: 泛泛管理理论 (商业书已覆盖, 本 skill 专谈 C-suite 这个具体岗位), 不含: 「领导力」作为个人成长自助 (Robbins/Tracy/Maxwell 励志体裁), 不含: 「如何创业」早期战术 — 一旦有员工 / 董事会 / 资本, CEO 的工艺才开始。"
WORKFLOW="WBR / 节奏运营 (Weekly Business Review & Operating Rhythm)"

usage() {
  cat <<EOF
wbr-weekly-business-review-opera.sh — Walk through "${WORKFLOW}" SOP for ${INDUSTRY}

逐步走完这个工作流的入门 SOP, 然后做失败模式自检, 输出走查报告。

USAGE:
  ./wbr-weekly-business-review-opera.sh             # interactive
  ./wbr-weekly-business-review-opera.sh --dry-run
  ./wbr-weekly-business-review-opera.sh --json
  ./wbr-weekly-business-review-opera.sh --explain
  ./wbr-weekly-business-review-opera.sh --help
EOF
}

explain() {
  cat <<'EOT'
这个 SOP 走查脚本帮你完成 "WBR / 节奏运营 (Weekly Business Review & Operating Rhythm)" 工作流。

一句话: 把公司当「人体」运行——周心跳 (WBR) + 月体检 (OP review) + 季度全身扫描 (QBR) + 年度战略 off-site。Amazon WBR (50-80 metric deep dive) + Mulally BPR (red/yellow/green 颜色化) + Grove staff meeting (operational vs strategic 分流) 三大范式合流，组成 CEO 看世界的运营仪表盘 + 异常发现机制。CEO 把 10-20% 时间花在 WBR 上是常态。 (evidence: [T03-S004, T03-S011, T03-S028, T03-S029, T03-S030])

入门 SOP 共 1 步, 失败模式自检 18 项。

相关心智模型:
  • 资本配置 = CEO 最高杠杆工作 (Capital Allocation as the #1 Job): 「CEO 一辈子要做的几十个决策中, 资本配置 (5 levers: 内部再投 / 并购 / 派息 / 回购 / 还债) 的复利结果决定企业 20 年后的市值排序; 不算 hurdle rate / 
  • 战略转折点 + 主动 paranoia (Strategic Inflection Point + Paranoia as Discipline): 「10x 力 (技术 / 竞争 / 监管 / 用户行为) 改变行业基本面时, CEO 必须最先识别 + 主动毁掉一部分老业务穿越 SIP (Intel 1985 退 DRAM / 任正非 1998 华

来源: research/03-workflows.md.
EOT
}

DRY_RUN=0; JSON=0
for arg in "$@"; do
  case "$arg" in
    --help|-h) usage; exit 0 ;;
    --explain) explain; exit 0 ;;
    --dry-run) DRY_RUN=1 ;;
    --json) JSON=1 ;;
  esac
done

declare -a SOP_STEPS=(
  "选 50-80 个 metric（financial 20 + product/operational 30-40 + people 10 + customer 10），Amazon 范式 input metric 优先（不是 output / lagging — 比如不是 revenue 是 conversion rate）；2. 每周一/周二 8am WBR（CEO 主持，SLT 全员到，CFO + 各产品/业务 owner 准备数据）；3. 异常深挖（red/yellow metric 现场要求 owner 解释 root cause + action — Mulally 范式：red 不被罚，被罚的是「red 没被报上来」）；4. action item assignment（每个 action 有 owner + due date + 下周 status）；5. 周三 staff 1:1（CEO 与 SLT 各 30-60 min — Grove 范式）；6. 周五 all-hands / Loom 视频（CEO 给全员 weekly 节奏 — Chesky / Patrick Collison 范式）；7. 月度 OP review（4 小时，OKR 进度 + 跨部门协调）；8. 季度 QBR（1-2 天，OKR 全公司复盘 + 致股东信草稿 + 下季展望）。"
)
declare -a FAILURE_MODES=(
  "\"Vanity dashboard\": 50-80 metric 全是 output / lagging（revenue / NPS / churn）但无 input metric → red 出现时太晚 (lagging metric 滞后 3-6 月才反映 input 变化)。"
  "触发原因: 财务出身 CEO 倾向 lagging metric / 没人 push input metric 建模。"
  "怎么避免: Amazon 范式 input metric 优先 (Bryar-Carr 详述: e.g. 不是 revenue 而是 detail page view per session × add-to-cart × checkout conversion × repeat purchase rate)。"
  "\"Don't shoot the messenger\" 违反: SLT 报 red 被 CEO 当场训 → 下次 red 被藏 → 12 月后小问题变大危机 (Mulally 接手 Ford 第一招就是发现「没人敢报 red」)。"
  "触发原因: CEO 习惯 problem-solving 模式，看到 red 第一反应是「为什么」(听起来像质问)。"
  "怎么避免: 显式宣布 + 第一次 red 给奖励 (Mulally 在 Ford 第一个报 red 的高管被公开表扬，next week 所有 dashboard 都有 red) + 区分「报告 red」(欢迎) vs 「解释 root cause + action」(要求)。"
  "\"Action item graveyard\": action 列了不 follow-up → 周复一周看同一 red → SLT 学会列 action 但不真做。"
  "触发原因: CEO 没有 action tracker / 周会节奏太赶。"
  "怎么避免: 每周开头复盘上周 action status (owner + done/in-progress/blocked) + blocked 立刻升级。"
  "\"WBR 变高管 alibi 会\": SLT 报数互相打太极，CEO 不深挖 → metric 数字漂亮但业务实际崩 (Wells Fargo cross-sell metric 漂亮但实际假账户 — WBR 失效经典)。"
  "触发原因: CEO 想保持 morale / 不愿被认为 micromanage。"
  "怎么避免: CEO 周期性深挖一个 owner 一个 metric (Bezos 范式 — 不预告，现场叫人解释为什么这条线 metric 是这样) + 不定期 skip-level (跳级问中层验证报数真实性)。"
  "\"Strategic vs operational 混\": staff meeting 既报数又拍战略，深度都不够 (Grove HOM 反复警告)。"
  "触发原因: 时间不够 / CEO 想一会议解决所有。"
  "怎么避免: 分流 — operational 高频短 (WBR 90 min) / strategic 低频长 (季度 QBR 1-2 天，年度 off-site 2-3 天) + 1:1 处理 SLT 个人议题。"
  "\"Cadence 不跟 stage 变\": 5 人时的 daily standup 用到 500 人 → SLT 信息淹没；500 人时的季度 review 用到 5 人 → 决策延迟。"
  "触发原因: 不主动 OS audit (workflow 8 范式)。"
  "怎么避免: 跨 stage 时 (workflow 8) 显式重写 meeting cadence — 100 / 500 / 2000 人坎都要审。"
)
declare -a STEP_STATUS=()
declare -a STEP_NOTES=()
declare -a FAIL_CHECK=()

ms_section "${INDUSTRY} · ${WORKFLOW} 走查"
ms_info "逐步走完 ${#SOP_STEPS[@]} 步入门 SOP。每步可标 done / skipped / blocked。"
echo

for i in "${!SOP_STEPS[@]}"; do
  ms_section "Step $((i+1))/${#SOP_STEPS[@]}: ${SOP_STEPS[$i]}"
  ms_prompt "状态? [d=done / s=skipped / b=blocked]"
  read -r status
  STEP_STATUS+=("${status:-d}")
  case "${status:-d}" in
    s) ms_prompt "跳过原因 (一句话):"; read -r note ;;
    b) ms_prompt "blocker (一句话):"; read -r note ;;
    *) note="" ;;
  esac
  STEP_NOTES+=("$note")
done

if [[ ${#FAILURE_MODES[@]} -gt 0 ]]; then
  ms_section "失败模式自检"
  for fm in "${FAILURE_MODES[@]}"; do
    if ms_confirm "你是否避免了 — '$fm' ?"; then
      FAIL_CHECK+=("✓ $fm")
    else
      FAIL_CHECK+=("✗ $fm")
    fi
  done
fi

ms_buffer_append "# ${INDUSTRY} — ${WORKFLOW} 走查报告"
ms_buffer_append ""
ms_buffer_append "_生成时间: $(date '+%Y-%m-%d %H:%M:%S')_"
ms_buffer_append ""
ms_buffer_append "## SOP 步骤"
ms_buffer_append ""
for i in "${!SOP_STEPS[@]}"; do
  status_icon="?"
  case "${STEP_STATUS[$i]}" in
    d|D) status_icon="✓" ;;
    s|S) status_icon="↷" ;;
    b|B) status_icon="✗" ;;
  esac
  if [[ -n "${STEP_NOTES[$i]}" ]]; then
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]} — ${STEP_NOTES[$i]}"
  else
    ms_buffer_append "$((i+1)). [${status_icon}] ${SOP_STEPS[$i]}"
  fi
done
ms_buffer_append ""
if [[ ${#FAIL_CHECK[@]} -gt 0 ]]; then
  ms_buffer_append "## 失败模式自检"
  ms_buffer_append ""
  for line in "${FAIL_CHECK[@]}"; do
    ms_buffer_append "- $line"
  done
  ms_buffer_append ""
fi

if [[ $JSON -eq 1 ]]; then
  ms_emit_json \
    "workflow" "${WORKFLOW}" \
    "step_count" "${#SOP_STEPS[@]}" \
    "failure_check_count" "${#FAILURE_MODES[@]}"
elif [[ $DRY_RUN -eq 1 ]]; then
  ms_emit_md_stdout
else
  ms_emit_md_file "wbr-weekly-business-review-opera-walkthrough"
fi
